### PR TITLE
CBG-2183: Fix replication panic w/ non-existent role in user role history

### LINKED ISSUE #5610: Panic due to null reference after non-existing role is removed from user
### Sync Gateway version
    {"couchdb":"Welcome","vendor":{"name":"Couchbase Sync Gateway","version":"3.0"},"version":"Couchbase Sync Gateway/3.0.3(1;8187d9a) CE"}

### Operating system
Azure AKS Kubernetes running container `couchbase/sync-gateway:3.0.3-community` - seems to be CentOS

### Config file
```
{
    "bootstrap": {
        "server": "couchbase://***",
        "use_tls_server": false,
        "username": "****",
        "password": "****"
    },
    "api": {
      "public_interface": ":4984",
      "admin_interface": ":4985",
      "metrics_interface": ":4986",
      "https": {}
    },
    "logging": {
        "log_file_path": "/var/tmp/sglogs",
        "console": {
            "enabled": true,
            "log_level": "info",
            "log_keys": [
                "*"
            ]
        }
    }
}
```

### Log output
Full output not available at the moment.  Null reference in go on [`user.go:380`](https://github.com/couchbase/sync_gateway/blob/3.0.3/auth/user.go#L380) when client tries to sync causes panic.  Repeated attempts cause crash loop & denial of service.

### Steps to reproduce
1.  Create user with `admin_roles` including two roles not previously defined (a1 and a2, for example)
2.  (unclear if required to trigger) reference role in sync function
3.  Update the user to not reference one of the roles (update to `['a1']`, for example)
4.  Try to sync from .net client
5.  Crash occurs

### Workaround
Create the non-existing role with request to the `PUT /{bucket}/_role/{role}` endpoint on admin API

### Expected behavior
Should not crash

### Actual behavior
It crashed

### PR DESCRIPTION
**Pull request by markspolakovs**
CBG-2183

`getPrincipal` returns a nil principal and nil error if the principal doesn't exist, but `ChannelGrantedPeriods` was missing a nil check. Add one with an appropriate log message, and add a regression test.

Fixes #5610.

## [Integration Tests](https://jenkins.sgwdev.com/job/SyncGateway-Integration/build?delay=0sec)
- [x] `xattrs=true` https://jenkins.sgwdev.com/job/SyncGateway-Integration/374/

### CODE REVIEW

File: rest/blip_api_test.go [hunk 1]
```diff
@@ -4494,3 +4494,40 @@ func TestBlipLegacyAttachDocUpdate(t *testing.T) {
 		require.Equal(t, keyValueErr.DocumentID, v2Key)
 	}
 }
+
+func TestBlipRevokeNonExistentRole(t *testing.T) {
```
Comment (markspolakovs) [inline rest/blip_api_test.go:4499]:
```suggestion
// Regression test for CBG-2183.
func TestBlipRevokeNonExistentRole(t *testing.T) {
```

**Review by bbrks — APPROVED** [review]
All seems reasonable - will let Adam have a look prior to merging.

**Review by adamcfraser — APPROVED** [review]
