### PR TITLE
Trigger doc import on SG write

### LINKED ISSUE #2554: XATTRs: SDK update not imported during SG write
### Sync Gateway version
1.4.2-364   

### Operating system
CentOS 7

### Config file
```
{
        "adminInterface": "0.0.0.0:4985",
        "compressResponses": false,
        "databases": {
            "db": {
                "bucket": "data-bucket",
                "password": "password",
                "server": "http://cbl.0:8091",
                "unsupported": {
                    "enable_extended_attributes": true
                }
            }
        },
        "interface": ":4984",
        "log": [
            "*"
        ],
        "maxCouchbaseConnections": 16,
        "maxFileDescriptors": 90000,
        "maxIncomingConnections": 0,
        "slowServerCallWarningThreshold": 500
    }
```

### Log output
https://gist.github.com/sethrosetter/3cc3daecf948a9ed276717f73ab402d3

### Expected behavior
On demand processing should happen for external updates (via SDK)

### Actual behavior
Doc is not processed and Sync Gateway is able to overwrite SDK changes

### Steps to reproduce
1.  Start SG with config above (auto-import is not enabled)
2. Write a doc via sync gateway (store rev#1)
3. Update that doc via SDK
4. Update the doc via sync gateway using rev=rev#1 (This should conflict due to on demand import of the SDK rev). It currently does not.

### PR DESCRIPTION
**Pull request by adamcfraser**
If a document has been updated by a non-SG author but has not yet been imported, trigger import on an attempt to update the doc via Sync Gateway. Fixes #2554.

Refactored the import processing to return the imported doc, so that on-demand imports can proceed without having to requery the bucket for the document.  Normal cas check will handle the case where the document is updated by someone else after import but before subsequent processing.

This cleans up the on-demand import during a GET (no longer requires loop), and avoids an unnecessary kv operation when on-demand import is triggered by a PUT.

Also fixed handling in change_cache.go when node is running in xattr mode but not importing.  Previously non-SG writes would attempt to get cached, then be rejected based on the stale sequence value.  Instead, we shouldn't even try to cache in the first place.

### CODE REVIEW

**Comment by adamcfraser** [comment]
Need to run the convergence functional tests to validate.

**Comment by adamcfraser** [comment]
Dependent PRs:
https://github.com/couchbaselabs/walrus/pull/30
https://github.com/couchbase/sg-bucket/pull/24
https://github.com/couchbaselabs/sync-gateway-accel/pull/145

**Comment by adamcfraser** [comment]
Functional tests look good.
http://uberjenkins.sc.couchbase.com/job/cen7-sync-gateway-functional-tests-base-cc/653/

 - failing ttl/expiry tests are waiting for pending server fix
 - test_view_backfill_for_deletes is test issue (intermittent failure)

File: db/crud.go [hunk 1]
```diff
@@ -854,41 +889,42 @@ func (db *Database) updateDoc(docid string, allowImport bool, expiry uint32, cal
...
+		var casOut uint64
+		casOut, err = db.Bucket.WriteUpdateWithXattr(key, KSyncXattrName, int(expiry), func(currentValue []byte, currentXattr []byte, cas uint64) (raw []byte, rawXattr []byte, deleteDoc bool, err error) {
 			// Be careful: this block can be invoked multiple times if there are races!
 			if doc, err = unmarshalDocumentWithXattr(docid, currentValue, currentXattr, cas); err != nil {
 				return
 			}
 
-			var updatedDoc *document
-			updatedDoc, _, shadowerEcho, err = documentUpdateFunc(doc, currentValue != nil)
+			docOut, _, shadowerEcho, err = documentUpdateFunc(doc, currentValue != nil)
```
Comment (tleyden) [inline db/crud.go]: It's a bit confusing to have a `shadowerEcho` when presumably this code could execute in an XATTR-only scenario w/ no bucket shadowing.  I realize this was already in the master branch, but what do you think about renaming this to something that doesn't sound bucket-shadowing specific?

File: db/crud.go [hunk 2]
```diff
@@ -854,41 +889,42 @@ func (db *Database) updateDoc(docid string, allowImport bool, expiry uint32, cal
...
 		}
 	} else {
 		err = db.Bucket.WriteUpdate(key, int(expiry), func(currentValue []byte) (raw []byte, writeOpts sgbucket.WriteOptions, err error) {
 			// Be careful: this block can be invoked multiple times if there are races!
 			if doc, err = unmarshalDocument(docid, currentValue); err != nil {
 				return
 			}
-			var updatedDoc *document
-			updatedDoc, writeOpts, shadowerEcho, err = documentUpdateFunc(doc, currentValue != nil)
+			docOut, writeOpts, shadowerEcho, err = documentUpdateFunc(doc, currentValue != nil)
```
Comment (tleyden) [inline db/crud.go:921]: ditto regarding `shadowerEcho`

**Review by tleyden — CHANGES_REQUESTED** [review]
See inline

File: db/crud.go (hunk 2 above)
Comment (adamcfraser) [reply db/crud.go:921]: I think this is the appropriate usage here (non-xattr flow)

File: db/crud.go (hunk 1 above)
Comment (adamcfraser) [reply db/crud.go]: Updated to omit shadowerEcho in this scenario.

File: base/bucket_gocb.go [hunk 3]
```diff
@@ -1182,7 +1183,7 @@ func (bucket CouchbaseBucketGoCB) WriteUpdateWithXattr(k string, xattrKey string
 			if !bucket.IsKeyNotFoundError(err) {
 				// Unexpected error, cancel writeupdate
 				LogTo("CRUD", "Retrieval of existing doc failed during WriteUpdateWithXattr for key=%s, xattrKey=%s: %v", k, xattrKey, err)
-				return err
+				return casOut, err
```
[the remark this answers is not in the document]
Comment (adamcfraser) [reply base/bucket_gocb.go]: Makes sense.

**Review by tleyden — APPROVED** [review]
