### PR TITLE
Fixes #2379 Move to latest gocb version and fixes #2376 add WriteUpdate

### LINKED ISSUE #2376: Add WriteUpdate (or equivalent) to gocb
Currently we don't have an implementation of [WriteUpdate](https://github.com/couchbase/go-couchbase/blob/18938d8dec422576a360ca7b8cca37d3d3d7358d/client.go#L1015) in the gocb bucket.  We need some flavour of "write w/ retry-on-CAS-fail" when writing through gocb.  

Implementing this as WriteUpdate would make it easier to drop in a gocb bucket as a replacement for a go-couchbase bucket, but need to review whether it's actually the right approach from a performance perspective.

### LINKED ISSUE #2379: Move to latest gocb version
Factored out of https://github.com/couchbase/sync_gateway/issues/2377

Need to add gocbcore repo to the manifest

### PR DESCRIPTION
**Pull request by tleyden**
This is a rework of PR https://github.com/couchbase/sync_gateway/pull/2387.  

Fixes #2379 
Fixes #2376 

# Functional tests

## CC

* [cen7-sync-gateway-functional-tests-base-cc/332/](http://uberjenkins.sc.couchbase.com/job/cen7-sync-gateway-functional-tests-base-cc/332/) - Passed
* [cen7-sync-gateway-functional-tests-topology-specific-cc/255](http://uberjenkins.sc.couchbase.com/job/cen7-sync-gateway-functional-tests-topology-specific-cc/255/) - Passed 

## DI

* [cen7-sync-gateway-functional-tests-base-di/297/](http://uberjenkins.sc.couchbase.com/job/cen7-sync-gateway-functional-tests-base-di/297/) - Passed with commit 97c5673f53a9f49125d078a33628d46424a8434a
* [cen7-sync-gateway-functional-tests-topology-specific-di/230/](http://uberjenkins.sc.couchbase.com/job/cen7-sync-gateway-functional-tests-topology-specific-di/230/) - Passed with commit 97c5673f53a9f49125d078a33628d46424a8434a

# Unit tests against running Couchbase server

## go-couchbase 

https://gist.github.com/tleyden/49f9ed16628969129f2ba8400291c48d

## gocb hybrid

https://gist.github.com/tleyden/f23407b07951602440306d6c7ef474ea

### CODE REVIEW

**Comment by tleyden** [comment]
Seeing failure on http://uberjenkins.sc.couchbase.com/job/cen7-sync-gateway-functional-tests-topology-specific-di/225/

In the ngrep logs for one of the sync gateways, here is the error that the functional test is reporting:

```

T 172.23.109.117:49879 -> 172.23.106.135:4984 [AP]
POST /db/_changes HTTP/1.1.
Host: sync_gateway.
Connection: close.
Content-Length: 75.
Accept-Encoding: gzip, deflate.
Accept: */*.
User-Agent: python-requests/2.9.1.
Cookie: SyncGatewaySession=cf7f19fbb7ec1489710437993be8b5cb741378de.
.
{"feed": "longpoll", "style": "all_docs", "since": "11-0", "timeout": 1000}
##
T 172.23.106.135:4984 -> 172.23.109.117:49879 [AP]
HTTP/1.1 500 Internal Server Error.
Content-Type: application/json.
Server: Couchbase Sync Gateway/1.4 branch/HEAD(nobranch) commit/3475e01.
Date: Thu, 23 Mar 2017 22:14:55 GMT.
Content-Length: 124.
Connection: close.
.
{"error":"Internal Server Error","reason":"Internal error: Stored hash not found for sequence [11-0], returning zero clock"}
########
```

Full ngrep logs on both Sync Gateways for this test:

https://gist.github.com/tleyden/9e97efa3aec0a74e34b1d142a167bccc

**Comment by tleyden** [comment]
Switching the code to use the default gocb transcoder for Gocb buckets seems to have fixed the issue (commit 97c5673f53a9f49125d078a33628d46424a8434a).  The sg transcoder is still used for hybrid buckets.

http://uberjenkins.sc.couchbase.com/job/cen7-sync-gateway-functional-tests-topology-specific-di/229/artifact/results/report.html

**Comment by tleyden** [comment]
All four functional test suites passing now -- @adamcfraser this should be ready for review.  Will file companion ticket for sg-accel repo

File: base/bucket.go [hunk 1]
```diff
@@ -561,3 +595,35 @@ func IsCasMismatch(bucket Bucket, err error) bool {
...
+		maxVbNo, err = bucket.GetMaxVbno()
+	case *CouchbaseBucketGoCBGoCouchbaseHybrid:
+		maxVbNo, err = bucket.GetMaxVbno()
+	case CouchbaseBucket:
+		maxVbNo, err = bucket.GetMaxVbno()
+	case *CouchbaseBucket:
+		maxVbNo, err = bucket.GetMaxVbno()
+	default:
+		Warn("Not a couchbase bucket - assuming walrus, setting maxVbNo=1024")
+	}
```
Comment (adamcfraser) [inline base/bucket.go]: Feels weird to have a switch that's handling 6 scenarios and making the same call for each one.  Does having multiple options in a single case work, or does that break the usage of bucket inside the case?

I realize this will be getting moved to the sg-bucket interface anyway, but could clean up, in case that work somehow gets deferred.

File: base/bucket_gocb.go [hunk 2]
```diff
@@ -898,23 +843,22 @@ func (bucket CouchbaseBucketGoCB) Update(k string, exp int, callback sgbucket.Up
...
 		// NOTE: ignore error and assume it's a "key not found" error.  If it's a more
 		// serious error, it will probably recur when calling other ops below
 
 		gocbExpvars.Add("Update_Get", 1)
-		cas, _ := bucket.Get(k, &value)
-
-		var callbackParam []byte
-		if value != nil {
-			callbackParam = value.([]byte)
+		cas, err := bucket.Get(k, &value)
```
Comment (adamcfraser) [inline base/bucket_gocb.go:853]: Do we want to call bucket.GetRaw here instead?   Particularly with the (temporary) fix that's mentioned in GetRaw?

File: base/bucket_gocb.go [hunk 3]
```diff
@@ -952,8 +896,85 @@ func (bucket CouchbaseBucketGoCB) Update(k string, exp int, callback sgbucket.Up
...
 func (bucket CouchbaseBucketGoCB) WriteUpdate(k string, exp int, callback sgbucket.WriteUpdateFunc) error {
-	LogPanic("Unimplemented method: WriteUpdate()")
-	return nil
+
+	bucket.singleOps <- struct{}{}
+	defer func() {
+		<-bucket.singleOps
+	}()
+
+	// The number of Couchbase Nodes that durable writes should be replicated to or persisted to
```
Comment (adamcfraser) [inline base/bucket_gocb.go]: Can you add a comment with the details on what replicateTo=0 and persistTo=1 mean, so that it's there in 6 months when we're looking at this again?

File: base/bucket_gocb.go [hunk 4]
```diff
@@ -952,8 +896,85 @@ func (bucket CouchbaseBucketGoCB) Update(k string, exp int, callback sgbucket.Up
...
+	numNodesReplicateTo := uint(0)
+	numNodesPersistTo := uint(1)
+
+	maxCasRetries := 100000 // prevent infinite loop
```
Comment (adamcfraser) [inline base/bucket_gocb.go]: This pattern (to avoid infinite looping) always reads like a bit of a hack to me.  I understand the motivation - a plain `for {` feels like it's inviting bugs, but the choice of 100000 feels arbitrary.

File: base/bucket_gocb.go [hunk 5]
```diff
@@ -952,8 +896,85 @@ func (bucket CouchbaseBucketGoCB) Update(k string, exp int, callback sgbucket.Up
...
+			return err
+		}
+
+		// Invoke callback to get updated value
+		value, writeOpts, err = callback(value)
+		if err != nil {
+			return err
+		}
+
+		if cas == 0 {
```
Comment (adamcfraser) [inline base/bucket_gocb.go:941]: Are we sure that a failing GET will always set the cas to zero?  It looks like the go-couchbase version is explicitly setting the cas to zero when it hits 'key not found'.
https://github.com/couchbase/gomemcached/blob/master/client/mc.go#L901

File: base/error.go [hunk 6]
```diff
@@ -38,6 +39,22 @@ func ErrorAsHTTPStatus(err error) (int, string) {
...
 		return 200, "OK"
 	}
+
+	switch err.Error() {
+	case gocbcore.ErrKeyNotFound.Error():
+		return http.StatusNotFound, "missing"
+	case gocbcore.ErrKeyExists.Error():
+		return http.StatusConflict, "Conflict"
+	case gocbcore.ErrTimeout.Error():
+		return http.StatusServiceUnavailable, "Database server is over capacity"
```
Comment (adamcfraser) [inline base/error.go]: Is 'over capacity' actually the appropriate message for a timeout error?  It might be the root cause, but maybe not in all cases?

File: base/error.go [hunk 7]
```diff
@@ -38,6 +39,22 @@ func ErrorAsHTTPStatus(err error) (int, string) {
...
+	case gocbcore.ErrOverload.Error():
+		return http.StatusServiceUnavailable, "Database server is over capacity"
+	case gocbcore.ErrBusy.Error():
+		return http.StatusServiceUnavailable, "Database server is over capacity"
+	case gocbcore.ErrTmpFail.Error():
+		return http.StatusServiceUnavailable, "Database server is over capacity"
+	}
+
```
Comment (adamcfraser) [inline base/error.go]: Generally I'm disappointed that we still end up having to do a string compare for gocb errors, instead of being able to include them in the type switch below.  Feels like there's the potential for confusion when one of the error types below happens to resolve to the same string as one of these gocbcore errors.

File: db/database.go [hunk 8]
```diff
@@ -330,24 +330,30 @@ func (context *DatabaseContext) NotifyUser(username string) {
...
 
 func (dc *DatabaseContext) TakeDbOffline(reason string) error {
-	base.LogTo("CRUD", "Taking Database : %v, offline", dc.Name)
+
 	dbState := atomic.LoadUint32(&dc.State)
+
+	// TODO: if we're taking the bucket offline, why aren't we closing the DCP feed?
+	// TODO: why aren't we calling dc.Close() here?  Where does it get called?
+
+	base.LogTo("CRUD", "Taking Database : %v, offline.  dbState: %v", dc.Name, dbState)
```
Comment (adamcfraser) [inline db/database.go]: Should this logging and TODOs be cleaned up now?

File: manifest/default.xml [hunk 9]
```diff
@@ -60,6 +61,10 @@
 
   <project name="gocb" path="godeps/src/github.com/couchbase/gocb" remote="couchbase" revision="67fb8fa4c62451372108f31c93034c07d9d9f4ab"/>
 
+  <project name="gocbcore" path="godeps/src/gopkg.in/couchbase/gocbcore.v2" remote="couchbase" revision="22d72f05785ba26be033aa8b6726435b5e50a7a0"/>
+
+  <project name="jsonx" path="godeps/src/gopkg.in/couchbaselabs/jsonx.v1" remote="couchbaselabs" revision="5b7baa20429a46a5543ee259664cc86502738cad"/>
+
```
Comment (adamcfraser) [inline manifest/default.xml:67]: Same question as above, about using gopkg.in vs. github.

**Review by adamcfraser — CHANGES_REQUESTED** [review]
Generally this looks good to me.  A few minor questions/style comments.  Have a look and let me know what you think.

File: auth/auth_test.go [hunk 10]
```diff
@@ -22,16 +22,14 @@ import (
...
-
 var gTestBucket base.Bucket
 
 func init() {
 	var err error
 	gTestBucket, err = base.GetBucket(base.BucketSpec{
-		Server:     kTestURL,
-		BucketName: "sync_gateway_tests"}, nil)
+		Server:          base.UnitTestUrl(),
+		CouchbaseDriver: base.DefaultDriverForBucketType[base.DataBucket],
```
[the remark this answers is not in the document]
Comment (tleyden) [reply auth/auth_test.go:31]: The only way I can see how to do that would be to switch calls over from:

```
base.BucketSpec{
		Server:          base.UnitTestUrl(),
		CouchbaseDriver: base.DefaultDriverForBucketType[base.DataBucket],
		BucketName:      "sync_gateway_tests"}
```

to:

```
base.NewBucketSpec(
    base.UnitTestUrl(),
    ... 
)
```

or perhaps a more "builder style" API.

Or do you see an easier way that keeps the `base.BucketSpec{...}` syntax?

File: base/bucket.go [hunk 11]
```diff
@@ -22,6 +22,7 @@ import (
 	memcached "github.com/couchbase/gomemcached/client"
 	sgbucket "github.com/couchbase/sg-bucket"
 	"github.com/couchbaselabs/walrus"
+	"gopkg.in/couchbase/gocbcore.v2"
```
[the remark this answers is not in the document]
Comment (tleyden) [reply base/bucket.go:25]: I initially tried to use `github.com/couchbase/gocbcore` but ran into issues, because within gocb it explicitly references `gopkg.in/couchbase/gocbcore...` and it could not find them in the `GOPATH`

I totally agree about using `github.com/couchbase/gocbcore`, but I don't think we can do this without upstream changes from gocb.

@brett19 if you have any insight on this, or if I'm missing something, let me know!  I can provide more details on the issue I ran into if needed.

File: base/bucket.go [hunk 12]
```diff
@@ -544,15 +578,15 @@ func IsCasMismatch(bucket Bucket, err error) bool {
 		return false
 	}
 
+	if err.Error() == gocbcore.ErrKeyExists.Error() {
+		return true
+	}
+
```
[the remark this answers is not in the document]
Comment (tleyden) [reply base/bucket.go]: Ok changing to:

```
func IsCasMismatch(bucket Bucket, err error) bool {
	if err == nil {
		return false
	}

	// GoCB handling
	if err.Error() == gocbcore.ErrKeyExists.Error() {
		return true
	}

	// GoCouchbase/Walrus handling
	if strings.Contains(err.Error(), "CAS mismatch") {
		return true
	}

	return false
}
```

File: base/bucket.go (hunk 1 above)
Comment (tleyden) [reply base/bucket.go]: > Does having multiple options in a single case work, or does that break the usage of bucket inside the case?

I just tried it:

* [Multiple options in single case gives an error](https://play.golang.org/p/mJtnjwPm4T): `typedThing.Hello undefined (type interface {} is interface with no methods)`
* [Standalone case options works](https://play.golang.org/p/CRwHBBNTQ-)

File: base/bucket_gocb.go (hunk 2 above)
Comment (tleyden) [reply base/bucket_gocb.go:853]: Great catch!  Will push up a change

File: base/bucket.go (hunk 1 above)
Comment (adamcfraser) [reply base/bucket.go]: Cool - thanks for checking.

File: base/bucket_gocb.go (hunk 3 above)
Comment (tleyden) [reply base/bucket_gocb.go]: Yup, done

File: auth/auth_test.go (hunk 10 above)
[the remark this answers is not in the document]
Comment (adamcfraser) [reply auth/auth_test.go:31]: No, you're right - I don't see a way to do it without adding complexity or obscuring what's going on.  Better to leave it explicit (as-is).

File: base/bucket_gocb.go (hunk 4 above)
Comment (tleyden) [reply base/bucket_gocb.go]: Agreed, this feels kludgy and confusing.  I changed to a plain `for {..}` until we can come up with a better way

File: base/bucket_gocb.go (hunk 5 above)
Comment (tleyden) [reply base/bucket_gocb.go:941]: I just noticed an issue while looking into this.

Currently we're calling:

```
if err != nil && err != gocb.ErrKeyNotFound {
```

but in my testing I found that this comparison doesn't work, since `gocb.ErrKeyNotFound` is actually a pointer and it doesn't seem to provide any guarantees that it will be returning a pointer to the same object.  I didn't actually look at the code, but from my testing that comparison approach wasn't reliable, which is why I switched to the string comparison approach.

I will push up a fix that uses the string comparison.

Comment (tleyden) [reply base/bucket_gocb.go:941]: > Are we sure that a failing GET will always set the cas to zero? 

I'm not sure.  Do you think we should switch this to call `IsKeyNotFoundError(err)`?

Comment (adamcfraser) [reply base/bucket_gocb.go:941]: That sounds like the right approach - use IsKeyNotFoundError, and then explicitly set the cas to zero if true.

File: base/error.go (hunk 6 above)
Comment (tleyden) [reply base/error.go]: Yeah agreed, that's misleading:

How about this?  It changes that message and adds a little more verbosity for the different "Database server is over capacity" errors

```
	switch err.Error() {
	case gocbcore.ErrKeyNotFound.Error():
		return http.StatusNotFound, "missing"
	case gocbcore.ErrKeyExists.Error():
		return http.StatusConflict, "Conflict"
	case gocbcore.ErrTimeout.Error():
		return http.StatusServiceUnavailable, "Database timeout error (gocbcore.ErrTimeout.Error)"
	case gocbcore.ErrOverload.Error():
		return http.StatusServiceUnavailable, "Database server is over capacity (gocbcore.ErrOverload.Error)"
	case gocbcore.ErrBusy.Error():
		return http.StatusServiceUnavailable, "Database server is over capacity (gocbcore.ErrBusy.Error)"
	case gocbcore.ErrTmpFail.Error():
		return http.StatusServiceUnavailable, "Database server is over capacity (gocbcore.ErrTmpFail.Error)"
	}
```

File: base/error.go (hunk 7 above)
Comment (tleyden) [reply base/error.go]: It gets a bit convoluted taking the gocb hybrid bucket into consideration.  We can catch up offline on that, but in the meantime I filed a ticket to get rid of that hybrid bucket: https://github.com/couchbase/sync_gateway/issues/2423

After that's done, I think we'll be in a better position to loop back to this error handling and make it more sane.

File: db/database.go (hunk 8 above)
Comment (tleyden) [reply db/database.go]: Ok done.  Did we ever figure out why we're not calling `db.Close()`?  Was that on purpose?

Comment (adamcfraser) [reply db/database.go]: I think we worked out that this call was just about changing the database state (with the accompanying change to the REST API behaviour), and not about actually closing the DB.  This allows it to be called from a variety of circumstances.

File: manifest/default.xml (hunk 9 above)
Comment (tleyden) [reply manifest/default.xml:67]: Here is a place where it's specifically referencing `gopkg.in` [in gocb](https://github.com/couchbase/gocb/blob/b1fd6be8f3a5dd3f1b5604cf0834113e2ce07cfe/cluster_query.go#L7)

I don't know of a way to get around doing the same.

Although .. I did notice that in branch-master.xml it [doesn't point to gopkg.in](https://github.com/couchbase/manifest/blob/master/branch-master.xml#L55), so maybe this is somehow possible.  

I'm actually more confused on why [branch-master.xml](https://github.com/couchbase/manifest/blob/master/branch-master.xml) doesn't even need to reference gocbcore, which makes me think it's not even being built

@ceejatec any idea?

Comment (ceejatec) [reply manifest/default.xml:67]: I'm guessing, but probably gocb isn't being built directly but is referenced by some other tool. And I guess whatever portions of gocb are used don't import the gocbore (or gopkg.in) stuff.

I do notice that the gocb reference in branch-master.xml is on the 'server-4.6' branch, so maybe that's an earlier version of the code which didn't have those dependencies?

File: base/bucket.go (hunk 11 above)
[the remark this answers is not in the document]
Comment (tleyden) [reply base/bucket.go:25]: Update: gocb currently points to a `gopkg.in` version of gocbcore in order to pin it to a known release when running `go get`.  Hopefully when the [saga of go dependency management](https://blog.gopheracademy.com/advent-2016/saga-go-dependency-management/) improves, the built-in go tooling will make this less clunky.

**Comment by tleyden** [comment]
@adamcfraser there's no more pending code changes, but the DI functional tests aren't passing on the latest commit.  I'm going to kick off re-runs and then chat with @sethrosetter if those fail too

**Comment by tleyden** [comment]
@adamcfraser looks like the DI functional tests were failing because they couldn't build, because it was trying to point to the current master branch of sync gateway accel.  I think we should merge and then look for the master branch build test results.  These tests did pass against a previous commit in the PR (97c5673f53a9f49125d078a33628d46424a8434a) and I linked to those tests in the top of the ticket
