### PR TITLE
Capture a shadower echo and use that do determine when to send notification events.

### LINKED ISSUE #2500: Webhook event not fired when using bucket shadowing
Commit ebb92f9, from PR #2014 introduced a regression that results in no WebHook events being fired for document updates triggerd by processing changes from a shadow bucket feed.

### PR DESCRIPTION
**Pull request by ajres**
fixes #2500

Capture when a shadower change is an echo and use that do determine when to send notification events.

### CODE REVIEW

**Comment by ajres** [comment]
NOTE: This does not function as expected on current master base because of the DCP Feed errors. It does function as expected on a previous master branch commit. 

Will need to be rebased on latest master once the DCP feed errors are resolved.

File: db/crud.go [hunk 1]
```diff
@@ -630,6 +630,9 @@ func (db *Database) updateDoc(docid string, allowImport bool, expiry uint32, cal
 			return
 		}
 
+		// Test for shadower echo here before UpstreamRev gets set to CurrentRev
+		shadowerEcho = doc.CurrentRev == doc.UpstreamRev
```
Comment (adamcfraser) [inline db/crud.go:634]: If I'm reading this properly, doc.CurrentRev and doc.Upstream rev are the incoming values here (because the callback doesn't mutate doc, it just returns body).

What happens for a new SDK write that's being imported for the first time?  Would doc.CurrentRev and doc.UpstreamRev both be nil in that case (and so incorrectly be identified as an echo)?

**Comment by adamcfraser** [comment]
Have a question about the processing logic, and am also wondering whether we can add a test to shadower_test.go to cover this functionality.

File: db/crud.go (hunk 1 above)
Comment (ajres) [reply db/crud.go:634]: Unit test added creates new docs in shadow, updates a shadow doc with no body change (echo) and updates a shadow doc with body change.
