### PR TITLE
#3765 Remove documents from channel caches on _purge or _compact

### LINKED ISSUE #1658: Purge doesn't remove cached documents
sync gateway _purge accepts revisions as \* to removes latest revision the document.  but i could also see that older documents are not deleted from couchbase. still i can get the older document . _purge not working with giving revision id in place of *.

### LINKED ISSUE #3765: Update cache on DCP delete mutations without xattrs
Currently Sync Gateway's feed processing [ignores delete mutations](https://github.com/couchbase/sync_gateway/blob/master/db/change_cache.go#L373) that don't have an associated xattr, as this doesn't represent a tombstone that needs to be replicated to clients.

However, this mutation may represent a purge of a document that's still resident in Sync Gateway's channel caches.  In that scenario, removing the entry from the cache will avoid potential replication overhead.

Unfortunately, since the delete mutation doesn't have the xattr associated with it, we don't have any visibility to channel membership for the document.  A brute force check of all active channels is required in order to purge the document from the cache.  Each cache already includes a hashmap of resident keys, so what's required is:
- iterate over changeCache.channelCaches
   - requires a read lock on changeCache.lock
- for each cache, check channelCache.cachedDocIDs for the key
   - requires a read lock on channelCache.lock
- delete the entry from the cache (remove from c.cachedDocIDs, c.logs, similar to what's done in pruneCache.  Note that this removal shouldn't require any changes to the cache's validFrom, since any associated sequence is no longer allocated to a revision
  - requires write lock on channelCache.lock

The performance overhead associated with this scan (particularly with the associated locking) is a potential concern.  There are a number of scenarios where a delete mutation wouldn't be expected to be found in the channel cache, resulting in scenarios where the work to check for the key in caches is just processing overhead.  These include:
- delete of documents that were never mobile-enabled (e.g. rejected by import filter)
- delete of documents that are no longer resident in the rev cache

To minimize the impact of the new delete processing on overall feed throughput, we could evaluate treating cache removal as an asynchronous process.  (i.e. stick the incoming event into a buffered channel in DocChangedSynchronous, and have a background worker goroutine process that channel.)  However, need to consider scenarios where a deleted doc gets resurrected - if the resurrected version gets cached before the delete is asynchronously processed, it would result in an invalid cache removal.

### PR DESCRIPTION
**Pull request by bbrks**
Fixes #3765 
Fixes #1658 

- Removes documents from channel caches on `_purge` or `_compact`

## Integration Tests
- [x] http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/807/
- [x] http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/808/

### CODE REVIEW

File: rest/admin_api_test.go [hunk 1]
```diff
@@ -1487,6 +1487,33 @@ func TestPurgeWithMultipleValidDocs(t *testing.T) {
...
+	var body map[string]interface{}
+	json.Unmarshal(resp.Body.Bytes(), &body)
+	assert.DeepEquals(t, body, map[string]interface{}{"purged": map[string]interface{}{"doc1": []interface{}{"*"}}})
+
+	changes, err = rt.WaitForChanges(1, "/db/_changes?filter=sync_gateway/bychannel&channels=abc", "", true)
+	assertNoError(t, err, "Error waiting for changes")
+	assert.Equals(t, changes.Results[0].ID, "doc2")
+
+}
+
```
Comment (adamcfraser) [inline rest/admin_api_test.go:1516]: A test to cover the start time handling would be useful here.

**Review by adamcfraser — CHANGES_REQUESTED** [review]

File: db/channel_cache.go [hunk 2]
```diff
@@ -173,6 +173,52 @@ func (c *channelCache) wouldBeImmediatelyPruned(change *LogEntry) bool {
...
+
+			// Make sure the document we're about to remove is older than the start time of the purge
+			// This is to ensure that resurrected documents do not accidentally get removed.
+			if c.logs[i].TimeReceived.After(startTime) {
+				base.Debugf(base.KeyCache, "Skipping removal of doc %q from cache %q - received after purge",
+					base.UD(docID), base.UD(c.channelName))
+				continue
+			}
+
+			// Memory-leak safe delete from SliceTricks:
```
Comment (adamcfraser) [inline db/channel_cache.go:208]: Validate this is safe for size 1 cache

File: rest/admin_api_test.go [hunk 3]
```diff
@@ -1487,6 +1487,33 @@ func TestPurgeWithMultipleValidDocs(t *testing.T) {
 	assertStatus(t, rt.SendRequest("PUT", "/db/doc2", `{"moo":"car"}`), 201)
 }
 
+// TestPurgeWithChanelCache will make sure thant upon calling _purge, the channel caches are also cleaned
+// This was fixed in #3765, previously channel caches were not cleaned up
+func TestPurgeWithChanelCache(t *testing.T) {
```
Comment (adamcfraser) [inline rest/admin_api_test.go]: Typo here

File: rest/admin_api_test.go [hunk 4]
```diff
@@ -1487,6 +1487,33 @@ func TestPurgeWithMultipleValidDocs(t *testing.T) {
...
+	// Purge "doc1"
+	resp := rt.SendAdminRequest("POST", "/db/_purge", `{"doc1":["*"]}`)
+	assertStatus(t, resp, http.StatusOK)
+	var body map[string]interface{}
+	json.Unmarshal(resp.Body.Bytes(), &body)
+	assert.DeepEquals(t, body, map[string]interface{}{"purged": map[string]interface{}{"doc1": []interface{}{"*"}}})
+
+	changes, err = rt.WaitForChanges(1, "/db/_changes?filter=sync_gateway/bychannel&channels=abc", "", true)
+	assertNoError(t, err, "Error waiting for changes")
+	assert.Equals(t, changes.Results[0].ID, "doc2")
```
Comment (adamcfraser) [inline rest/admin_api_test.go:1513]: Add verification for channel def as well

File: rest/admin_api_test.go (hunk 1 above)
Comment (bbrks) [reply rest/admin_api_test.go:1516]: Added `TestChannelCacheRemove` to cover startTime logic

File: db/channel_cache.go (hunk 2 above)
Comment (bbrks) [reply db/channel_cache.go:208]: Tested manually in https://play.golang.org/p/qpQ82e8aCQ_C

File: rest/admin_api_test.go (hunk 4 above)
Comment (bbrks) [reply rest/admin_api_test.go:1513]: done

**Review by adamcfraser — APPROVED** [review]

**Comment by erpankaj22** [comment]
I have a question on this release. Where the documents were deleted by using expiry function on sync gateway. And meta data purge interval is 1.25 days. Will sync gateway remove this documents from the channel cache after 1.25 days automatically now or we will need to run _compact.

**Comment by bbrks** [comment]
@erpankaj22 with `enable_shared_bucket_access` set, you will need to run _compact occasionally to clear the channel caches for documents removed via expiry/TTLs.
