### PR TITLE
Return removed=true for non-resident channel removal revisions

### LINKED ISSUE #2815: Removed revisions returning 404 missing instead of _removed
When a client issues a GET for a revision that is a removal from a channel the user has access to, Sync Gateway should return the document in the format:
```
{
    "_id": "someDoc", 
    "_removed": true, 
    "_rev": "2-985ace42e53e2e447549d34abdb3c7ae"
}
```

If the document is not the active revision, isn't resident in the revision cache, and the temporary document body backup has expired, Sync Gateway is instead returning  `404 missing`.  This will cause CBL to fail to update the document as removed (although there will be improved client handling in 2.0 via https://github.com/couchbase/couchbase-lite-core/issues/212).

Sync Gateway should use the channel history on the document to properly return the _removed entry in all scenarios.

### PR DESCRIPTION
**Pull request by adamcfraser**
When an revision is requested, but that revision's body is no longer available (it's not resident in the rev cache, and the temporary revision backup has expired), check whether that revision is associated with a channel removal based on the document's channel history.  If it's a removal, return the standard removal notification body (_removed=true) instead of 404 missing.

Fixes #2815.

### CODE REVIEW

**Comment by tleyden** [comment]
Looks good, but per [Boy Scout Rule](http://pragmaticcraftsman.com/2011/03/the-boy-scout-rule/), can the naked returns be changed to have explicit params?

```
if doc, err = context.GetDoc(id.DocID); doc == nil {
		return
	}
```

replaced w/ 

```
if doc, err = context.GetDoc(id.DocID); doc == nil {
		return  body, history, channels, err
	}
```

**Comment by tleyden** [comment]
Also in the interest of keeping the unit / integration tests green, I kicked one off and I think we should wait until it passes:

http://uberjenkins.sc.couchbase.com/view/Build/job/build-sync-gateway/223/

**Review by tleyden — CHANGES_REQUESTED** [review]
See comments

File: db/database_test.go [hunk 1]
```diff
@@ -257,6 +257,79 @@ func TestGetDeleted(t *testing.T) {
...
+	assertNoError(t, err, "Put")
+
+	rev2body := Body{
+		"key1":     1234,
+		"channels": []string{"NBC"},
+		"_rev":     rev1id,
+	}
+	rev2id, err := db.Put("doc1", rev2body)
+	assertNoError(t, err, "Put Rev 2")
+
```
Comment (ajres) [inline db/database_test.go:361]: Maybe add the case where rev2 is tombstoned (_deleted)

File: db/database_test.go [hunk 2]
```diff
@@ -257,6 +257,79 @@ func TestGetDeleted(t *testing.T) {
 	assert.DeepEquals(t, body, expectedResult)
 }
 
+// Test retrieval of a channel removal revision, when the revision is not otherwise available
+func TestGetRemoved(t *testing.T) {
```
Comment (ajres) [inline db/database_test.go]: Add an equivalent test for named user rather than admin

**Review by tleyden — APPROVED** [review]

**Comment by tleyden** [comment]
LGTM -- @ajres had a suggestion on improving the test
