### PR TITLE
#3549 Change _sgcollect_info endpoint zip filename format for Windows compatibility

### LINKED ISSUE #3549: Incompatible Windows filename from _sgcollect_info endpoint
Windows doesn't allow colons in file names, so the new `_sgcollect_info` endpoint fails, as it tries to write a file with the format: `sgcollect_info_2018-05-10T04:19:13.212-07:00.zip`

```
2018-05-10T04:20:01.533-07:00 [DBG] Admin+: sgcollect_info: [8832] Failed to execute script sgcollect_info
2018-05-10T04:20:01.534-07:00 [DBG] Admin+: sgcollect_info: Traceback (most recent call last):
2018-05-10T04:20:01.534-07:00 [DBG] Admin+: sgcollect_info:   File "sgcollect_info", line 792, in <module>
2018-05-10T04:20:01.534-07:00 [DBG] Admin+: sgcollect_info:   File "sgcollect_info", line 767, in main
2018-05-10T04:20:01.534-07:00 [DBG] Admin+: sgcollect_info:   File "tasks.py", line 336, in zip
2018-05-10T04:20:01.534-07:00 [DBG] Admin+: sgcollect_info:   File "tasks.py", line 367, in _zip_helper
2018-05-10T04:20:01.534-07:00 [DBG] Admin+: sgcollect_info:   File "tasks.py", line 371, in _zip_fallback
2018-05-10T04:20:01.534-07:00 [DBG] Admin+: sgcollect_info:   File "zipfile.py", line 756, in __init__
2018-05-10T04:20:01.534-07:00 [DBG] Admin+: sgcollect_info: IOError: [Errno 22] invalid mode ('wb') or filename: 'sgcollect_info_2018-05-10T04:19:13.212-07:00.zip'
2018-05-10T04:20:01.554-07:00 [WRN] Admin: sgcollect_info failed after 62.5ms with reason: exit status 4294967295. Check debug logs with log key 'Admin' for more detail. -- rest.(*sgCollect).Start.func2() at sgcollect.go:87
```

### PR DESCRIPTION
**Pull request by bbrks**
Fixes #3549 

Change filename output of `_sgcollect_info` endpoint for Windows compatibility. Aligns with server's cbcollect_info filename format of `sgcollectinfo-2018-05-10t133456-sg@203.0.113.123.zip`

### CODE REVIEW

File: rest/sgcollect.go [hunk 1]
```diff
@@ -200,8 +203,41 @@ func sgCollectPaths() (sgPath, sgCollectPath string) {
...
+
+// sgcollectFilename returns a Windows-safe filename for sgcollect_info zip files.
+func sgcollectFilename() string {
+
+	// get timestamp
+	timestamp := time.Now().UTC().Format("2006-01-02t150405")
+
+	// Use a shortened product name as username.
+	// This may change, so the unit test for sgcollectFilename explicitly checks one of these is set.
+	name := "ProductName"
```
Comment (adamcfraser) [inline rest/sgcollect.go]: Default to "sg"

**Review by adamcfraser — COMMENTED** [review]
Minor change, otherwise looks good.

File: rest/sgcollect.go (hunk 1 above)
Comment (bbrks) [reply rest/sgcollect.go]: Done

**Review by adamcfraser — APPROVED** [review]
