### PR TITLE
Add expvar, fix termination of async changes goroutines

### LINKED ISSUE #3225: Continuous changes started by blipsync not terminated when connection is closed
I used [sg-blip](https://github.com/couchbaselabs/sg-blip) to open a continuous changes feed over blip:

screen shot 2018-01-18 at 4 52 35 pm

However, the expars showed the active changes feeds at 0:

screen shot 2018-01-18 at 4 52 45 pm

Currently that expvar seems to be updated in the REST handler, and might need to be moved down to `generateContinuousChanges()`

## Tasks

- [ ] Modify code to update expvar in this case
- [ ] Verify that when BLIP clients disconnect, the number of active changes goes down

### PR DESCRIPTION
**Pull request by adamcfraser**
Adds expvars for blip continuous changes goroutines (subChanges_total, subChanges_active), as well as the goroutine launched for internal changes processing (simpleChanges_total, simpleChanges_active).  The latter is used by both blipsync and normal continuous replication.

Fixes terminator handling for continuous changes started by blip, and fixes teardown processing.

Fixes #3225

### CODE REVIEW

**Comment by adamcfraser** [comment]
Integration tests:
http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/345/
http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/346/

File: rest/blip_sync.go [hunk 1]
```diff
@@ -237,7 +245,15 @@ func (bh *blipHandler) handleSubscribeToChanges(rq *blip.Message) error {
 	} else if filter != "" {
 		return base.HTTPErrorf(http.StatusBadRequest, "Unknown filter; try sync_gateway/bychannel")
 	}
-	go bh.sendChanges(rq.Sender, since) // TODO: does this ever end?
+
+	// Start asynchronous changes goroutine
+	go func() {
+		base.StatsExpvars.Add("subChanges_total", 1)
+		base.StatsExpvars.Add("subChanges_active", 1)
+		defer base.StatsExpvars.Add("subChanges_active", -1)
```
Comment (tleyden) [inline rest/blip_sync.go]: I think it's more idiomatic to put the `defer` statement at the top of the function, or as close to the top as possible.

File: rest/blip_sync.go [hunk 2]
```diff
@@ -296,6 +311,12 @@ func (bh *blipHandler) sendChanges(sender *blip.Sender, since db.SequenceID) {
 		}
 		return nil
 	})
+
+	// On forceClose, send notify to trigger immediate exit from change waiter
+	if forceClose && bh.user != nil {
+		bh.db.DatabaseContext.NotifyUser(bh.user.Name())
```
Comment (tleyden) [inline rest/blip_sync.go:340]: I think `NotifyUser` is a really confusing function name.  This might be a good time to rename this to something more descriptive.  How about `DatabaeContext.StopChangeWaiter(username string)`?  That seems a lot more inline with the comment "trigger immediate exit from change waiter"

File: rest/changes_api.go [hunk 3]
```diff
@@ -659,14 +660,20 @@ loop:
 			forceClose = true
 			break loop
 		case <-closeNotify:
-			base.LogTo("Changes", "Connection lost from client: %v", h.currentEffectiveUserName())
+			if h != nil {
+				base.LogTo("Changes+", "Client connection lost: %v", h.currentEffectiveUserName())
```
Comment (tleyden) [inline rest/changes_api.go]: I think this code would be simpler / clearer as:

```
currentUser := "unknown"
if h != nil {
    currentUser = h.currentEffectiveUserName()
}
base.LogTo("Changes+", "Client connection lost.  User: %v", currentUser)
```

**Review by tleyden — CHANGES_REQUESTED** [review]

**Comment by tleyden** [comment]
Looks like the integration test for non-xattrs failed with:

```
2018-02-01T09:28:47.377-08:00 Waiting for shadower to catch up...
_time=2018-02-01T09:28:47.411-08:00 _level=INFO _msg=Using plain authentication for user test_shadowbucket 
2018-02-01T09:28:47.466-08:00 Shadow: Pushing "key1", rev "1-9e3cca3549437556aa5123af76d4f749"
2018-02-01T09:28:47.466-08:00 Shadow: Pushing "key2", rev "1-12571c0bd5457a77255c38b1460275fd"
2018-02-01T09:28:47.478-08:00 Deleting local doc
2018-02-01T09:28:47.480-08:00 Shadow: Pushing "key1", rev "2-533e44d1a283bfda509c40c7b5667d01" [deletion]
--- FAIL: TestShadowerPush (24.80s)
	revtree_test.go:989: shadower_test.go:204: Timeout!
```

Seems like it might be a sporadic failure, but I kicked off a re-run in http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/351/

**Comment by adamcfraser** [comment]
Looks like 351 is clean - I'll rebase on master.

**Comment by adamcfraser** [comment]
Rebased on master, waiting for drone

File: rest/blip_sync.go (hunk 2 above)
Comment (adamcfraser) [reply rest/blip_sync.go:340]: The 'Notify' part of NotifyUser is important, because it's a reminder that this is just doing a broadcast over the tapNotifier - it's not doing any kind of synchronous stop of the user's changeWaiter.

I agree that the User part is bad - the current implementation doesn't even use the provided username, and should be refactored to get rid of that and just be NotifyTerminate.  It feels a bit risky to be tweaking for 2.0, though.  I could open a PR for dev/2.1 with that change, though.

File: rest/blip_sync.go (hunk 1 above)
Comment (adamcfraser) [reply rest/blip_sync.go]: In this case we shouldn't execute the defer unless the previous StatsExpvars.Add was successful, so I think we want to leave this as-is.

**Review by tleyden — APPROVED** [review]
