### PR TITLE
Fixes #2854 remove legacy import

### LINKED ISSUE #2854: Remove legacy import handling in assimilator.go
### Sync Gateway version
1.5.0-538

### Operating system
CentOS 7.2

### Config file
```javascript
{
  "log":[
    "*",
    "Import+"
  ],
  "databases":{
    "db":{
      "users":{
        "GUEST":{
          "disabled":false,
          "admin_channels":[
            "*"
          ]
        },
        "testuser":{
          "admin_channels":[
            "ch_testuser"
          ],
          "password":"ch_password"
        }
      },
      "server": "http://Administrator:password@172.23.108.103:8091",
      "bucket":"default",
      "password":"password",
      "import_docs":"continuous",
      "unsupported":{
        "enable_extended_attributes":true,
        "replicator_2":true
      }
    }
  }
}
```

### Log output
https://gist.github.com/tahmmee/7b5b1be3fb932127877392f194c881d6

### Expected behavior
Expected Gateway to start.

### Actual behavior
Panic occurs

### Steps to reproduce
1.  Start the sg against default bucket
2.  Run the mobile testkit's dotnet container against the gateway
3.  Run background loaders with binary & json docs against same default bucket
4.  Loop step #2 for ~4 days
5.  Stop sync gateway and try to start again

* Note the reason for step 5 was that I noticed somehow we had 3 instances of the gateway running against the bucket.

### PR DESCRIPTION
**Pull request by tleyden**
Fixes #2854 

- [ ] Merge SG accel PR: https://github.com/couchbaselabs/sync-gateway-accel/pull/201

## Integration tests

http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/505/consoleFull

Failures:

- TestN1qlQuery
- TestChannelView
- TestPostUpgradeIndexesSimple

None of these appear to be related to importing

## Docs

Docs ticket: https://issues.couchbase.com/browse/DOC-3488

### CODE REVIEW

File: rest/config.go [hunk 1]
```diff
@@ -121,7 +121,7 @@ type DbConfig struct {
 	Users                        map[string]*db.PrincipalConfig `json:"users,omitempty"`                        // Initial user accounts
 	Roles                        map[string]*db.PrincipalConfig `json:"roles,omitempty"`                        // Initial roles
 	RevsLimit                    *uint32                        `json:"revs_limit,omitempty"`                   // Max depth a document's revision tree can grow to
-	ImportDocs                   interface{}                    `json:"import_docs,omitempty"`                  // false, true, or "continuous"
+	ImportDocs                   interface{}                    `json:"import_docs,omitempty"`                  // The only valid value if this is provided is "continuous".  Xattrs must be enabled.
```
Comment (tleyden) [inline rest/config.go]: Any reason not to change to a `*string`?

I didn't try that in the first pass just to keep the PR as minimal of a change as possible, but since the only valid values are now `nil` and "continuous", maybe it makes sense.  Thoughts welcome.

**Comment by tleyden** [comment]
Looks like this PR broke some bucket shadowing functionality.  Reworking.

**Comment by tleyden** [comment]
I pushed some additional commits that re-establish the bucket shadowing functionality.  Ready for a review pass.

File: rest/config.go (hunk 1 above)
Comment (adamcfraser) [reply rest/config.go]: Ideally we'd simplify it to boolean at this point - 'continuous' is really just a relic of the old options.  We probably need to continue to support 'continuous' for backward compatibility, but I think we should also treat true==continuous and false==nil.

File: rest/server_context.go [hunk 2]
```diff
@@ -358,14 +358,12 @@ func (sc *ServerContext) _getOrAddDatabaseFromConfig(config *DbConfig, useExisti
 
 	var importDocs, autoImport bool
 	switch config.ImportDocs {
-	case nil, false:
-	case true:
-		importDocs = true
+	case nil:
 	case "continuous":
 		importDocs = true
```
Comment (adamcfraser) [inline rest/server_context.go]: We can remove 'importDocs' here, right?

File: db/assimilator.go [hunk 3]
```diff
@@ -21,29 +19,7 @@ func (c *DatabaseContext) watchDocChanges() {
 				if c.Shadower != nil {
 					c.Shadower.PushRevision(doc)
 				}
-			} else {
-				if c.autoImport {
```
Comment (adamcfraser) [inline db/assimilator.go:25]: Can we remove c.autoImport altogether?

**Review by adamcfraser — CHANGES_REQUESTED** [review]

File: rest/config.go (hunk 1 above)
Comment (tleyden) [reply rest/config.go]: Fixed

File: db/assimilator.go (hunk 3 above)
Comment (tleyden) [reply db/assimilator.go:25]: Merged ImportDocs and autoImport into the same variable throughout the codebase.  The legacy config support is provided via keeping the name in the json as `import_docs`

File: rest/server_context.go (hunk 2 above)
Comment (tleyden) [reply rest/server_context.go]: Yes, importDocs is removed since it was combined w/ the `autoImport` variable

**Comment by tleyden** [comment]
@adamcfraser ready for another pass

**Comment by tleyden** [comment]
Requires an SG accel change due to variable rename: couchbaselabs/sync-gateway-accel#201

**Review by adamcfraser — APPROVED** [review]
Looks great.  I've merged the accel PR - just need to bump the manifest commit here.
