### PR TITLE
Attempt to make gocb bucket flushable

### LINKED ISSUE #3305: Bucket flush endpoint doesn't work against Couchbase server buckets
When trying to run https://github.com/couchbase/sync_gateway/issues/3286 against Sync Gateway backed by Couchbase server, I noticed that the bucket flush endpoint was not working.

### PR DESCRIPTION
**Pull request by tleyden**
**Not ready for merge** -- will need to first merge the dependent PR in the sg-bucket repo

Fixes https://github.com/couchbase/sync_gateway/issues/3305 (dev branch)

## Changes:

- Add `CloseAndDelete()` (aka "flush") method to `gocb_bucket.go`, as well as `BucketItemCount()` helper method needed by `CloseAndDelete()`
- Update `handleFlush()` to properly handle the flush so it doesn't try to flush a closed bucket.  Manually verified that this still works against Walrus.
- Add unsupported config flag + check in `handleFlush()` to force the user to set a flag if flushing a Couchbase bucket via REST API
- Refactor out a `GetBucketSpec()` method
- [x] Merge the dependent PR in the sg-bucket repo: https://github.com/couchbase/sg-bucket/pull/34

## Post merge

- [ ] Update the LiteCore replication tests to enable couchbase server buckets to be flushed

### CODE REVIEW

File: base/bucket_gocb.go [hunk 1]
```diff
@@ -2112,6 +2113,110 @@ func (bucket CouchbaseBucketGoCB) Close() {
...
+	if err != nil {
+		return err
+	}
+
+	workerFlush := func() (shouldRetry bool, err error, value interface{}) {
+		err = bucketManager.Flush()
+		if err != nil {
+			Warn("Error flushing bucket: %v  Will retry.", err)
+		}
+		shouldRetry = (err != nil) // retry (until max attempts) if there was an error
```
Comment (bbrks) [inline base/bucket_gocb.go]: Could move up into the block above and simplify: `shouldRetry = true`

File: rest/api.go [hunk 2]
```diff
@@ -64,19 +64,61 @@ func (h *handler) handleVacuum() error {
...
+			// Flush
+			err := tempBucketForFlush.CloseAndDelete()
+			if err != nil {
+				return err
+			}
+
+		}
+
+		// Close the temporary connection to the bucket that was just for purposes of flushing it
+		tempBucketForFlush.Close()
```
Comment (bbrks) [inline rest/api.go]: If we return an error from `tempBucketForFlush.CloseAndDelete()`, we'll never close the bucket. Could we defer the close after successfully connecting to the bucket instead?

**Review by bbrks — CHANGES_REQUESTED** [review]
I think we might be leaving the temp bucket open in some cases.

File: base/bucket_gocb.go [hunk 3]
```diff
@@ -2112,6 +2113,110 @@ func (bucket CouchbaseBucketGoCB) Close() {
...
+	if err != nil {
+		return -1, err
+	}
+	req.Header.Add("Content-Type", "application/json")
+
+	user, pass, _ := bucket.spec.Auth.GetCredentials()
+
+	req.SetBasicAuth(user, pass)
+
+	resp, err := http.DefaultClient.Do(req)
```
Comment (adamcfraser) [inline base/bucket_gocb.go]: I don't think using http.DefaultClient is sufficient here.  Would this handle HTTPS connections, couchbase: schemes, etc?

We've got at least one other case (putDDocForTombstones) that builds a custom API call to Couchbase Server, but uses the bucket's existing endpoints and HTTP client.  You could reuse that approach here, or potentially extract it into a more generic function.

File: rest/api.go (hunk 2 above)
Comment (adamcfraser) [inline rest/api.go]: If this is a walrus bucket, won't we panic here trying to close an already closed bucket?

File: rest/server_context.go [hunk 4]
```diff
@@ -292,13 +292,54 @@ func (sc *ServerContext) getOrAddDatabaseFromConfig(config *DbConfig, useExistin
...
+	feedType := strings.ToLower(config.FeedType)
+
+	couchbaseDriver := base.ChooseCouchbaseDriver(base.DataBucket)
+
+	var viewQueryTimeoutSecs *uint32
+	if config.ViewQueryTimeoutSecs != nil {
+		viewQueryTimeoutSecs = config.ViewQueryTimeoutSecs
+	}
+
+	// Connect to the bucket and add the database:
```
Comment (adamcfraser) [inline rest/server_context.go]: This comment doesn't apply any more.

File: rest/server_context.go [hunk 5]
```diff
@@ -409,6 +430,12 @@ func (sc *ServerContext) _getOrAddDatabaseFromConfig(config *DbConfig, useExisti
 
 	}
 
+	// Connect to the bucket and add the database:
+	spec, err := GetBucketSpec(config)
+	if err != nil {
+		return nil, err
+	}
+
```
Comment (adamcfraser) [inline rest/server_context.go:429]: Some of the functionality looks like it's now duplicated in GetBucketSpec and _getOrAddDatabaseFromConfig (pool/server/bucketname calculations - potentially just for use in logging?).

**Review by adamcfraser — CHANGES_REQUESTED** [review]
See inline comments/questions.

File: base/bucket_gocb.go (hunk 1 above)
Comment (tleyden) [reply base/bucket_gocb.go]: Good catch

File: rest/api.go (hunk 2 above)
Comment (tleyden) [reply rest/api.go]: Fixed.  Perfect use of defer()!

File: base/bucket_gocb.go [hunk 6]
```diff
@@ -2112,6 +2113,110 @@ func (bucket CouchbaseBucketGoCB) Close() {
 	}
 }
 
+// This flushes the bucket but doesn't actually close the bucket, despite the name CloseAndDelete(),
+// which is based on the sgbucket.DeleteableBucket interface.
```
[the remark this answers is not in the document]
Comment (tleyden) [reply base/bucket_gocb.go]: I agree this was confusing.   I added a "Flushable" interface, and so now it first checks that and calls `.Flush()`:

https://github.com/couchbase/sync_gateway/blob/c7fa80e0bc42a84c1dfd135602f32cb0a82915c3/rest/api.go#L66-L137

File: base/bucket_gocb.go (hunk 3 above)
Comment (tleyden) [reply base/bucket_gocb.go]: Fixed

File: rest/api.go (hunk 2 above)
Comment (tleyden) [reply rest/api.go]: After the last round of changes, it won't hit this code in the walrus case, since walrus supports the DeletableBucket interface

File: rest/server_context.go (hunk 4 above)
Comment (tleyden) [reply rest/server_context.go]: Removed

File: rest/server_context.go (hunk 5 above)
Comment (tleyden) [reply rest/server_context.go:429]: Fixed by using the fields in GetBucketSpec

**Comment by tleyden** [comment]
@adamcfraser ready for another pass.  Also see https://github.com/couchbase/sg-bucket/pull/34

**Comment by tleyden** [comment]
- Rebased on master and fixed the logging related conflict.
- Pointed to latest sg-bucket master commit

@adamcfraser ready for another review pass

**Comment by tleyden** [comment]
The build failed because the sg-bucket commit hadn't gotten merged.  Pushed a new commit and the build is in progress.

**Review by bbrks — DISMISSED** [review]
It all looks OK, but would be nice to use the new logging functions to save another round of find+replace.

File: base/bucket_gocb.go [hunk 7]
```diff
@@ -2150,6 +2151,119 @@ func (bucket *CouchbaseBucketGoCB) Close() {
...
+
+	bucketManager, err := bucket.getBucketManager()
+	if err != nil {
+		return err
+	}
+
+	workerFlush := func() (shouldRetry bool, err error, value interface{}) {
+		err = bucketManager.Flush()
+		if err != nil {
+			Warn("Error flushing bucket: %v  Will retry.", err)
```
[the remark this answers is not in the document]
Comment (tleyden) [reply base/bucket_gocb.go]: Fixed

File: base/bucket_gocb.go [hunk 8]
```diff
@@ -2150,6 +2151,119 @@ func (bucket *CouchbaseBucketGoCB) Close() {
...
+			// Bucket flushed, we're done
+			break
+		}
+
+		if numTries > maxTries {
+			return fmt.Errorf("Timed out waiting for bucket to be empty after flush.  ItemCount: %v", itemCount)
+		}
+
+		// Still items left, wait a little bit and try again
+		Warn("TestBucketManager.EmptyBucket(): still %d items in bucket after flush, waiting for no items.  Will retry.", itemCount)
```
[the remark this answers is not in the document]
Comment (tleyden) [reply base/bucket_gocb.go]: Fixed

**Comment by tleyden** [comment]
Ready for another review pass

File: base/bucket_gocb.go [hunk 9]
```diff
@@ -2141,6 +2142,119 @@ func (bucket *CouchbaseBucketGoCB) Close() {
...
+
+}
+
+// GOCB doesn't currently offer a way to do this, and so this is a workaround to go directly
+// to Couchbase Server REST API.
+// See https://forums.couchbase.com/t/is-there-a-way-to-get-the-number-of-items-in-a-bucket/12816/4
+// for GOCB discussion.
+// NOTE: unfortunately this code was duplicated with TestBucketManager.BucketItemCount() since TestBucketManager
+// holds a reference to a *gocb.Bucket, but not a CouchbaseBucketGoCB wrapper.  If this code could get
+// pushed down into *gocb.Bucket, then both methods could be removed.
```
[the remark this answers is not in the document]
Comment (tleyden) [reply base/bucket_gocb.go]: Fixed

File: base/bucket_gocb.go [hunk 10]
```diff
@@ -2141,6 +2142,119 @@ func (bucket *CouchbaseBucketGoCB) Close() {
...
+	err, _ = RetryLoop("EmptyTestBucket", workerFlush, CreateDoublingSleeperFunc(12, 10))
+	if err != nil {
+		return err
+	}
+
+	maxTries := 20
+	numTries := 0
+	for {
+
+		itemCount, err := bucket.BucketItemCount()
```
[the remark this answers is not in the document]
Comment (tleyden) [reply base/bucket_gocb.go]: Fixed

File: base/bucket_gocb.go [hunk 11]
```diff
@@ -2141,6 +2142,119 @@ func (bucket *CouchbaseBucketGoCB) Close() {
...
+	return int(itemCountFloat), nil
+
+}
+
+func (bucket *CouchbaseBucketGoCB) goCBHttpClient() *http.Client {
+
+	goCBClient := bucket.Bucket.IoRouter()
+	return goCBClient.HttpClient()
+
+}
```
[the remark this answers is not in the document]
Comment (tleyden) [reply base/bucket_gocb.go]: Yes, I think all of the calls to `Bucket.IoRouter()` should be changed to check for nils and return errors rather than panicking.  I didn't do it as part of this PR though since it's a bit outside the scope, and I don't know how likely it is to happen in practice.

[the remark this answers is not in the document]
Comment (tleyden) [reply base/bucket_gocb.go]: This helper function did get removed though since it was no longer being used after a previous change.

File: db/database.go [hunk 12]
```diff
@@ -110,9 +110,14 @@ type UserViewsOptions struct {
 	Enabled *bool `json:"enabled,omitempty"` // Whether pass-through view query is supported through public API
 }
 
+type APIEndpoints struct {
+	EnableCouchbaseBucketFlush bool `json:"enable_couchbase_bucket_flush,omitempty"` // Whether Couchbase buckets can be flushed via Admin REST API
```
[the remark this answers is not in the document]
Comment (tleyden) [reply db/database.go]: Thanks for catching that.  Yeah I think this is a great place to document the "why" and justify this field's existence.

File: rest/api.go [hunk 13]
```diff
@@ -64,7 +64,60 @@ func (h *handler) handleVacuum() error {
...
+
+
+	// If it can be flushed, then flush it
+	if _, ok := h.db.Bucket.(sgbucket.FlushableBucket); ok {
+
+		// If it's not a walrus bucket, don't allow flush unless the unsupported config is set
+		if !h.db.BucketSpec.IsWalrusBucket() {
+			if !h.db.DatabaseContext.AllowFlushNonCouchbaseBuckets() {
+				msg := "Flush not allowed on Couchbase buckets by default.  You must explicitly enable the ability to flush " +
+					"Couchbase buckets via the Unsupported option: api_endpoints/enable_couchbase_bucket_flush"
```
[the remark this answers is not in the document]
Comment (tleyden) [reply rest/api.go]: Removed for public safety reasons.

**Comment by tleyden** [comment]
Integration tests:

http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/515/
http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/516/

**Comment by tleyden** [comment]
Ready for another review pass

**Comment by tleyden** [comment]
Integration test failures: http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/516/consoleFull

@adamcfraser any chance you can do a quick triage on these to see if they look like they were newly introduced?

**Comment by adamcfraser** [comment]
I haven't seen TestBulkDocsUnusedSequencesMultipleSG fail like that before - it looks like it's not setting num_replica=0 (which TestBucket should do by default).

File: base/bucket_gocb.go [hunk 14]
```diff
@@ -2380,3 +2438,47 @@ func (bucket *CouchbaseBucketGoCB) releaseViewOp() {
 	<-bucket.viewOps
 	gocbExpvars.Add("ViewOps", -1)
 }
+
+func GoCBBucketItemCount(bucket *gocb.Bucket, spec BucketSpec, user, pass string) (itemCount int, err error) {
+
+	reqUri := fmt.Sprintf("%s/pools/default/buckets/%s", spec.Server, spec.BucketName)
```
Comment (adamcfraser) [inline base/bucket_gocb.go]: Does this work if spec.Server is 'couchbase://'?  

I think it would be preferable to use goCBClient.MgmtEps to get this endpoint - it feels more reliable.

**Review by adamcfraser — CHANGES_REQUESTED** [review]
One question about the use of Spec.Server vs. getting endpoints from gocb.

**Comment by tleyden** [comment]
> I haven't seen TestBulkDocsUnusedSequencesMultipleSG fail like that before - it looks like it's not setting num_replica=0 (which TestBucket should do by default).

One possibility is that this test creates a second DB on the fly which doesn't have the correct parameters (num_replicas, SG_TEST_USE_XATTRS)

File: base/bucket_gocb.go (hunk 14 above)
Comment (tleyden) [reply base/bucket_gocb.go]: Fixed in 2cb91a569f34292d8a3c3d03b076585f343fd7da

**Comment by tleyden** [comment]
I kicked off another integration test after the latest commit: https://github.com/couchbase/sync_gateway/pull/3333/commits/2cb91a569f34292d8a3c3d03b076585f343fd7da

Passed: http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/524/

**Review by adamcfraser — APPROVED** [review]
LGTM

**Comment by tleyden** [comment]
Rebased on master, waiting for the build to finish and will merge
