### PR TITLE
Only log value of new logging logFilePath if it has been set.

### LINKED ISSUE #2367: Omitting the logFilePath property in the logging configuration of Sync Gateway results in a null pointer exception crash
omitting logFilePath results in null pointer exception crash.
What i was trying to accomplish: Use the new config syntax but only log to stdout/stderr (eg. have systemd/journalctl handle writing the log output to file instead of sync gateway handling its own log files)

Aside: It would also be nice if the systemd unit files stopped redirecting stdout/stderr and instead let systemd handle log capture itself.

### Version info

SG Version: couchbase-sync-gateway-1.4.0-2.x86_64
OS: Centos 7.3.1611

### Config file
relevant config file partial
```javascript
    "logging": {
        "default": {
            "logKeys": ["CRUD", "HTTP"],
            "logLevel": "info"
        }
    }
```

### Log output
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x483d6a]

goroutine 1 [running]:
panic(0xa84cc0, 0xc420010060)
	/usr/local/go/1.7.4/go/src/runtime/panic.go:500 +0x1a1
github.com/couchbase/sync_gateway/base.CreateRollingLogger(0xc4201b44e0)
	/home/couchbase/jenkins/workspace/sgw-unix-build@2/1.4.0/community/godeps/src/github.com/couchbase/sync_gateway/base/logging.go:574 +0x11a
github.com/couchbase/sync_gateway/rest.(*ServerConfig).setupAndValidateLogging(0xc420175680, 0x0, 0xb44bea, 0xe)
	/home/couchbase/jenkins/workspace/sgw-unix-build@2/1.4.0/community/godeps/src/github.com/couchbase/sync_gateway/rest/config.go:482 +0x1ac
github.com/couchbase/sync_gateway/rest.ParseCommandLine(0x401700)
	/home/couchbase/jenkins/workspace/sgw-unix-build@2/1.4.0/community/godeps/src/github.com/couchbase/sync_gateway/rest/config.go:666 +0x985
github.com/couchbase/sync_gateway/rest.ServerMain(0xc400000000)
	/home/couchbase/jenkins/workspace/sgw-unix-build@2/1.4.0/community/godeps/src/github.com/couchbase/sync_gateway/rest/config.go:813 +0x2a
main.main()
	/home/couchbase/jenkins/workspace/sgw-unix-build@2/1.4.0/community/godeps/src/github.com/couchbase/sync_gateway/main.go:34 +0xf5
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x483d6a]
```

### Expected behavior
[Documentation](https://developer.couchbase.com/documentation/mobile/1.4/guides/sync-gateway/config-properties/index.html#default) says without a logFilePath, the server should default to logging to stderr (presumably as long as log rotation is not defined).

### Actual behavior

crash

### PR DESCRIPTION
**Pull request by ajres**
Fixes #2367 

This is a fix for the panic in SG when the logging section config does not contain a logFIlePath

In this case SG should log to stderr

### CODE REVIEW

File: base/logging.go [hunk 1]
```diff
@@ -550,15 +550,17 @@ func NewLoggerWriter(logKey string, serialNumber uint64, req *http.Request) *Log
 
 func CreateRollingLogger(logConfig *LogAppenderConfig) {
 	if logConfig != nil {
+		SetLogLevel(logConfig.LogLevel.sgLevel())
+
 		lj := lumberjack.Logger{}
 
-		if logConfig.LogFilePath != nil {
+		if logConfig.LogFilePath == nil {
```
Comment (adamcfraser) [inline base/logging.go]: I found this logic a little bit hard to follow at first read (we create the lumberjack logger, THEN abort when LogFilePath == nil - it took me a minute to work out whether we were using the rolling logger or not)

What do you think about doing the "if LogFilePath==nil" check right after SetLogLevel, and then just fall through to the rest?
