### PR TITLE
Correct CAS retry handling for import based on import type

### LINKED ISSUE #2672: XAttrs: Updates reverted during concurrent Sync Gateway / SDK writes
The Sync Gateway issue tracker is reserved for bug reports and enhancement 
requests. For general questions, please use the Couchbase forums:
https://forums.couchbase.com/c/mobile/sync-gateway. Thank you!

### Sync Gateway version
1.5.0-441

### Operating system
CentOS 7

### Config file
```javascript
{
        "adminInterface": "0.0.0.0:4985",
        "compressResponses": false,
        "databases": {
            "db": {
                "bucket": "data-bucket",
                "import_docs": "continuous",
                "password": "password",
                "server": "http://cbl.0:8091",
                "unsupported": {
                    "enable_extended_attributes": true
                },
                "username": "data-bucket"
            }
        },
        "interface": ":4984",
        "log": [
            "CRUD+",
            "Cache+",
            "HTTP+",
            "Changes+"
        ],
        "maxCouchbaseConnections": 16,
        "maxFileDescriptors": 90000,
        "maxIncomingConnections": 0,
        "slowServerCallWarningThreshold": 500
    }
```

### Expected behavior
I would expect that SG (new edits=False) SDK (CAS safe writes) would error if one of the clients had mutated the doc underneath the other

### Actual behavior
Sync Gateway is blowing away some SDK updates

### Steps to reproduce
1. `pytest -s --skip-provisioning --xattrs --ci --mode=cc --server-version=5.0.0-3158 --sync-gateway-version=1.5.0-441 -k "test_sg_sdk_interop_shared_docs[sync_gateway_default_functional_tests-1-1000]" testsuites/syncgateway/functional/tests/`

### PR DESCRIPTION
**Pull request by adamcfraser**
Feed-based imports shouldn't be retried on CAS failures - the subsequent mutation will be imported if needed.

On-demand imports need to be retried on CAS failure, so that the subsequent SG operation is working against the correct version of the document.

Fixes #2672

Requires https://github.com/couchbaselabs/sync-gateway-accel/pull/152

### CODE REVIEW

File: db/crud.go [hunk 1]
```diff
@@ -635,6 +642,18 @@ func (db *Database) ImportDoc(docid string, body Body, isDelete bool) (docOut *d
 			return nil, nil, base.ErrAlreadyImported
 		}
 
+		// If there's a cas mismatch, the doc has been updated since the version that triggered the import.  Handling depends on import mode
+		if doc.Cas != importCas {
```
Comment (tleyden) [inline db/crud.go]: // At the point we know it's an SDK write (as opposed to SG write), since we checked if SG write above
