### PR TITLE
Fixes #844 Retrieving a non existent design doc returns 500 error

### LINKED ISSUE #844: Retrieving a non existent design doc returns 500 error
It looks like Couchbase server is correctly responding with a 404, but Sync Gateway is failing to parse that response and is returning a 500 error (with a message containing `Internal error: Error reading view: 404 Object Not Found`!)

To reproduce:

```
curl -X GET http://localhost:4985/unit_tests/_design/testDoc
```

 …where `_design/testDoc` does not exist in the bucket (`unit_tests`)

Sync Gateway logs:

```
14:59:37.527771 HTTP:  #250: GET /unit_tests/_design/testDoc  (ADMIN)
14:59:37.527802 TEMP: GetDesignDoc "testDoc" -- rest.(*handler).handleGetDesignDoc() at view_api.go:17
14:59:37.529077 WARNING: Couldn't interpret error type *errors.errorString, value Error reading view: 404 Object Not Found / {"error":"not_found","reason":"deleted"}
 -- base.ErrorAsHTTPStatus() at error.go:63
14:59:37.529114 HTTP: #250:     --> 500 Internal error: Error reading view: 404 Object Not Found / {"error":"not_found","reason":"deleted"}
  (1.3 ms)
```

### PR DESCRIPTION
**Pull request by tleyden**
Fixes #844 

After this change, if trying to get a non-existent design doc, it returns a 404 error w/ a json body:

```
{
    "error": "not_found",
    "reason": "missing"
}
```

### CODE REVIEW

File: rest/view_api.go [hunk 1]
```diff
@@ -29,6 +30,11 @@ func (h *handler) handleGetDesignDoc() error {
 		result = db.Body{"filters": db.Body{"bychannel": filter}}
 	} else {
 		if err := h.db.GetDesignDoc(ddocID, &result); err != nil {
+			// GoCB doesn't provide an easy way to distinguish what the cause of the error was, so
+			// resort to a string pattern match for "not_found" and propagate a 404 error in that case.
+			if strings.Contains(err.Error(), "not_found") {
+				return base.HTTPErrorf(404, "%v","missing")
+			}
```
Comment (adamcfraser) [inline rest/view_api.go]: The gocb error introspection will be easier to maintain if we push this error checking down into CouchbaseBucketGoCB.GetDDoc, and returned a new ErrNotFound SGError that we could check for here.

**Review by adamcfraser — CHANGES_REQUESTED** [review]

File: rest/view_api.go (hunk 1 above)
Comment (tleyden) [reply rest/view_api.go]: Good catch, fixed.

Comment (tleyden) [reply rest/view_api.go]: Actually, some more work needed to create and return `ErrNotFound `

**Comment by tleyden** [comment]
Ready for another pass

**Review by adamcfraser — APPROVED** [review]
