### PR TITLE
Fixes #2760 - Allow Facebook registration without Email address

### LINKED ISSUE #2760: Sync Gateway Facebook Login email is missing
I am raising this as an Issue as Jens suggested on below post.
https://forums.couchbase.com/t/sync-gateway-facebook-login-email-is-missing/13553

Hello,
I have checked other forums but could not identify the solution of below problem.

Currently we have many users who are using Facebook through their mobile number and not using email at all. Those can not login to my app as Sync Gateway Throws the error saying email is missing. Indeed their tokens do not have email.

2017-07-24T11:54:46.928+05:30 HTTP: #38388: --> 400 Cannot register new user: email is missing (104.8 ms)

Is there any way I can bypass this so that users can use the app only using facebook id?

We are using below

### Sync Gateway version
Sync Gateway Community edition : 1.4.1

### Operating system
Ubuntu 14

iOS/Android Mobile Client: 1.4

### Steps to reproduce
1.  Try to Login with Facebook using userId which does not have email

### PR DESCRIPTION
**Pull request by bbrks**
Fixes #2760 - Allow Facebook registration without Email address

- Modified `handler.makeSessionFromNameAndEmail()` for cases where no email is present
- Fixes some outdated comments

# Integration Tests
- http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/258/
- http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/259/

### CODE REVIEW

File: rest/session_api.go [hunk 1]
```diff
@@ -157,10 +158,39 @@ func (h *handler) makeSessionFromEmail(email string, createUserIfNeeded bool) er
...
 		}
 	}
+
 	return h.makeSession(user)
 
 }
 
+// makeSessionFromName attempts to find the user by username.
+// If not found, and createUserIfNeeded=true, creates a new user based on username.
+func (h *handler) makeSessionFromName(username string, createUserIfNeeded bool) error {
```
Comment (adamcfraser) [inline rest/session_api.go]: I don't think we need a parallel creation option - I think it's sufficient to modify MakeSessionFromUserAndEmail to allow an empty email when in the create processing.  It looks like the only other caller is for google auth, and we don't need to enforce email there either.

**Review by adamcfraser — CHANGES_REQUESTED** [review]
I think it's sufficient to tweak the existing handling, instead of creating a separate path just for the no email case.

File: rest/session_api.go (hunk 1 above)
Comment (bbrks) [reply rest/session_api.go]: OK, makes sense if we want that behaviour for the Google auth flow too. I've updated the PR with those changes.

File: rest/session_api.go [hunk 2]
```diff
@@ -166,45 +168,43 @@ func (h *handler) makeSessionFromEmail(email string, createUserIfNeeded bool) er
...
+		// If user found, check whether the email needs to be updated
+		// (e.g. user has changed email in external auth system)
+		if user != nil && email != user.Email() {
+			if err = user.SetEmail(email); err == nil {
 				h.db.Authenticator().Save(user)
 			}
 		}
-	} else {
-		// User not found by name.  Attempt user lookup by email.  This provides backward
+
```
Comment (adamcfraser) [inline rest/session_api.go]: I think you lost an 'else' here - we don't want to fall through to the email-based user lookup unless user was nil.

**Review by adamcfraser — CHANGES_REQUESTED** [review]

File: rest/session_api.go [hunk 3]
```diff
@@ -182,13 +182,12 @@ func (h *handler) makeSessionFromNameAndEmail(username, email string, createUser
...
 				h.db.Authenticator().Save(user)
 			}
-		}
-
-		// User not found by username. Attempt user lookup by email. This provides backward
-		// compatibility for users that were originally created with id = email
-		user, err = h.db.Authenticator().GetUserByEmail(email)
-		if err != nil {
-			return err
+		} else {
```
Comment (adamcfraser) [inline rest/session_api.go]: I think this needs to be `else if user == nil`.  Otherwise we'll attempt to re-lookup the user when the user's found and the email matches.

**Review by adamcfraser — CHANGES_REQUESTED** [review]

File: rest/session_api.go (hunk 3 above)
Comment (bbrks) [reply rest/session_api.go]: Thanks, my attempt at reducing the nesting obviously impacted my ability to parse it well. Restored original code, and wrapped in the extra if.
