### PR TITLE
Fix cache backfill after active-only view query

### LINKED ISSUE #2955: View query triggered by active-only changes results in incomplete channel cache
When a channel cache is initialized by an active-only changes feed, it appears to be only adding the active-only results to the channel cache.  Subsequent non-active-only changes requests are missing deleted/removed documents.

Reported when testing against a walrus bucket as part of client unit tests.

### PR DESCRIPTION
**Pull request by adamcfraser**
Fixes #2955  

Active-only evaluation during channel view query should only be used for limit calculation, and shouldn't determine the set of entries returned (which are prepended to the cache and used for subsequent non-active-only requests).

### CODE REVIEW

File: rest/changes_api_test.go [hunk 1]
```diff
@@ -1112,6 +1111,159 @@ func TestChangesActiveOnlyWithLimit(t *testing.T) {
...
+		Results  []db.ChangeEntry
+		Last_Seq interface{}
+	}
+
+	// Pre-delete changes
+	changesJSON := `{"style":"all_docs"}`
+	changesResponse := it.Send(requestByUser("POST", "/db/_changes", changesJSON, "bernard"))
+	err = json.Unmarshal(changesResponse.Body.Bytes(), &changes)
+	assertNoError(t, err, "Error unmarshalling changes response")
+	assert.Equals(t, len(changes.Results), 5)
```
Comment (tleyden) [inline rest/changes_api_test.go:1142]: Is there potential races between calling `it.SendAdminRequest("POST", "/db/_bulk_docs"` and the changes from `it.Send(requestByUser("POST", "/db/_changes", changesJSON, "bernard"))` having all the expected changes?  In particular, during integration tests.

If so, can this be re-worked to do a retry loop so that it's robust against races?  I've been running into this issue a lot as part of https://github.com/couchbase/sync_gateway/issues/2938

**Review by tleyden — CHANGES_REQUESTED** [review]

File: rest/changes_api_test.go [hunk 2]
```diff
@@ -1112,6 +1111,159 @@ func TestChangesActiveOnlyWithLimit(t *testing.T) {
...
+	response = it.SendAdminRequest("PUT", "/db/activeDoc2", `{"channel":["PBS"]}`)
+	assertStatus(t, response, 201)
+	response = it.SendAdminRequest("PUT", "/db/activeDoc3", `{"channel":["PBS"]}`)
+	assertStatus(t, response, 201)
+	response = it.SendAdminRequest("PUT", "/db/activeDoc4", `{"channel":["PBS"]}`)
+	assertStatus(t, response, 201)
+	response = it.SendAdminRequest("PUT", "/db/activeDoc5", `{"channel":["PBS"]}`)
+	assertStatus(t, response, 201)
+
+	time.Sleep(100 * time.Millisecond)
```
Comment (tleyden) [inline rest/changes_api_test.go]: Can you document why this sleep is needed?  And ideally replace it w/ a retry loop if it's solving a race condition?

File: rest/changes_api_test.go (hunk 1 above)
Comment (tleyden) [reply rest/changes_api_test.go:1142]: In another branch, I added some code that does a retry loop waiting for changes:

https://github.com/couchbase/sync_gateway/commit/5c46825d7bc0904da7fd8616622b00bdcf9b4715

It's the restTester rather than the indexTester though

File: db/changes_view.go [hunk 3]
```diff
@@ -66,26 +67,26 @@ func (dbc *DatabaseContext) getChangesInChannelFromView(
...
-			} else {
-				entries = append(entries, entry)
 			}
+			entries = append(entries, entry)
 			optMap["startkey"] = []interface{}{channelName, entry.Sequence + 1}
 		}
 
 		if options.ActiveOnly {
-			if len(entries) >= options.Limit || options.Limit == 0 {
+			if activeEntryCount >= options.Limit || options.Limit == 0 {
```
Comment (tleyden) [inline db/changes_view.go]: I'm struggling to understand this code.  Can you add a comment to explain why it breaks out of the for loop in this case?

Also I think early breaks would be easier to understand .. eg,:

```
if !options.ActiveOnly {
   // No need to keep iterating, because the requirement to loop until we have consumed limit log entries only applies to ActiveOnly
   break
}

if options.ActiveOnly && activeEntryCount >= options.Limit || options.Limit == 0 {
   // no need to continue, because we need to loop until we have consumed limit log entries
   break
}
```

File: rest/changes_api_test.go [hunk 4]
```diff
@@ -1112,6 +1111,159 @@ func TestChangesActiveOnlyWithLimit(t *testing.T) {
...
+	// Create a conflict, and don't tombstone it
+	response = it.SendAdminRequest("POST", "/db/_bulk_docs", `{"docs":[{"_id":"conflictedDoc","channel":["PBS"], "_rev":"1-conflictActive"}], "new_edits":false}`)
+	assertStatus(t, response, 201)
+
+	var changes struct {
+		Results  []db.ChangeEntry
+		Last_Seq interface{}
+	}
+
+	// Pre-delete changes
```
Comment (tleyden) [inline rest/changes_api_test.go]: Can you change this comment to "verify all of the changes before the delete happens later in the test"

File: rest/changes_api_test.go [hunk 5]
```diff
@@ -1112,6 +1111,159 @@ func TestChangesActiveOnlyWithLimit(t *testing.T) {
...
+	for _, entry := range changes.Results {
+		log.Printf("Entry:%+v", entry)
+		// validate conflicted handling
+		if entry.ID == "conflictedDoc" {
+			assert.Equals(t, len(entry.Changes), 2)
+		}
+	}
+}
+
+func TestChangesActiveOnlyWithLimitAndViewBackfill(t *testing.T) {
```
Comment (tleyden) [inline rest/changes_api_test.go]: Can the test header have a link to the issue that it reproduces?

Comment (adamcfraser) [reply rest/changes_api_test.go]: I included that on the specific section of the test - not sure it's needed on the header as well, but could add a header explaining what this test is all about.

File: rest/changes_api_test.go [hunk 6]
```diff
@@ -1183,6 +1335,9 @@ func TestChangesActiveOnlyWithLimit(t *testing.T) {
 	}
 
 	// Active only NO Limit, POST
+	testDb := it.ServerContext().Database("db")
+	testDb.FlushChannelCache()
```
Comment (tleyden) [inline rest/changes_api_test.go]: I think it's worth calling out why the `FlushChannelCache()` is being run since it's crucial to the test.  I guess it forces a view requery which surfaces the bug?

File: rest/changes_api_test.go (hunk 5 above)
Comment (tleyden) [reply rest/changes_api_test.go]: Oh, n/m, I see that only a certain section is dedicated to reproducing this issue and that's called out

File: rest/changes_api_test.go (hunk 6 above)
Comment (adamcfraser) [reply rest/changes_api_test.go]: I'll stick that in the test header

File: db/changes_view.go (hunk 3 above)
Comment (adamcfraser) [reply db/changes_view.go]: Added comments to explain it.  Didn't use early breaks, because I think it makes the second if statement a lot harder to parse.

**Review by tleyden — APPROVED** [review]

**Comment by tleyden** [comment]
LGTM

**Comment by tleyden** [comment]
Integration tests:

http://uberjenkins.sc.couchbase.com/view/Build/job/build-sync-gateway/294/
http://uberjenkins.sc.couchbase.com/view/Build/job/build-sync-gateway/295/
