### PR TITLE
Fixes #2857: Revision tree repair tool 

### LINKED ISSUE #2857: Revision tree repair tool
To repair the revision trees with cycles caused by https://github.com/couchbase/sync_gateway/issues/2847

- [x] Dry run mode
- [x] Call Import View to walk keys (UpdateAllDocChannels) -- current doc path
- [x] Cas safe write if identified changes
- [x] Instructions: Take bucket offline, do changes, then restart.  Solves stale revcache issue.
- [x] Wire up to endpoint

## Instructions

See https://github.com/couchbase/sync_gateway/wiki/Issue-2857-Repair-Tool

## Test Instructions

- Run Couchbase Server 4.x, with empty `data-bucket` bucket
- Run Sync Gateway with [this config](https://gist.github.com/tleyden/935ffaa7b4c82703f50ea3f89d8bb402)
- `wget https://gist.githubusercontent.com/tleyden/bc4d9cae6ac8bfe408c373e673ff58e9/raw/659700bc6287ed44cdd8158a9e8a82a33cb80e08/data_for_test`
- `cbc cp data_for_test -U couchbase://localhost/data-bucket`
- Verify that the doc has cycles in revtree by running `curl http://{{host}}:{{port_admin}}/{{db}}/data_for_test?revs=true` and looking for `"reason": "Internal error: getHistory found cycle in revision tree`
- Repair the bucket via the [instructions](https://github.com/couchbase/sync_gateway/wiki/Issue-2857-Repair-Tool)

### PR DESCRIPTION
**Pull request by tleyden**
Adds a tool to repair the revision trees with cycles caused by https://github.com/couchbase/sync_gateway/issues/2847

Instructions + Test Instructions are [in the beginning of issue 2847](https://github.com/couchbase/sync_gateway/issues/2857#issue-253501830)

### CODE REVIEW

**Comment by tleyden** [comment]
@snej we have a question regarding this check:

```

// Repair rev trees that have cycles introduced by SG Issue #2847
func (tree RevTree) Repair() (err error) {

	// This function will be called back for every leaf node in tree
	leafProcessor := func(leaf *RevInfo) {

               ... 

		for {

			if node.ParentGenLargerNodeGen() {
				base.Warn("Node %+v detected to have invalid parent rev.  Repairing by designating as a root node.", node)
				node.Parent = ""
				break
			}

                        ...

		}
	}

	// Iterate over leaves
	tree.forEachLeaf(leafProcessor)

	return nil
}

// Detect situations like:
//     node: &{ID:10-684759c169c75629d02b90fe10b56925 Parent:184-a6b3f72a2bc1f988bfb720fec8db3a1d Deleted:fa...
// where the parent generation is *higher* than the node generation, which is never a valid scenario.
func (node RevInfo) ParentGenLargerNodeGen() bool {
	return genOfRevID(node.Parent) > genOfRevID(node.ID)
}
```

The only scenario that we know about that might end up creating parent generations that violate this assumption and are valid is if a user went to the Sync Gateway REST API directly and PUT a document with `new_edits=false`, and could set arbitrary revision id's, possibly including arbitrary revision generation numbers.  (not 100% sure about this)

Aside from that, do you know of any cases where Couchbase Lite would create a revision in the rev tree where the generation was out of order?

**Comment by snej** [comment]
>do you know of any cases where Couchbase Lite would create a revision in the rev tree where the generation was out of order?

No; it should be an invariant that a child revision's generation is greater than its parent's. I just checked the source code for the special case where you PUT a doc with no revID, and the doc used to exist but was deleted; the new revision becomes a child of the deletion rev and gets its gen + 1.

File: db/repair_bucket.go [hunk 1]
```diff
@@ -0,0 +1,228 @@
...
+// Params suitable for external (eg, HTTP) invocations to describe a RepairBucket operation
+type RepairBucketParams struct {
+	DryRun     bool              `json:"dry_run"`
+	RepairJobs []RepairJobParams `json:"repair_jobs"`
+}
+
+// Params suitable for external (eg, HTTP) invocations to describe a specific RepairJob operation
+type RepairJobParams struct {
+	RepairJobType   RepairJobType          `json:"repair_job_type"`
+	RepairJobParams map[string]interface{} `json:"repair_job_params"`
```
Comment (adamcfraser) [inline db/repair_bucket.go]: Since these are nested inside the 'repair_jobs' element, should we skip the 'repair_job_' prefix on the json names?

File: db/repair_bucket.go [hunk 2]
```diff
@@ -0,0 +1,228 @@
+package db
+
+import (
+	"encoding/json"
+
+	"io/ioutil"
```
Comment (adamcfraser) [inline db/repair_bucket.go]: Imports need formatting.

File: db/repair_bucket.go [hunk 3]
```diff
@@ -0,0 +1,228 @@
...
+			}
+			updatedDoc, shouldUpdate, err := r.TransformBucketDoc(doc)
+			if err != nil {
+				return nil, err
+			}
+
+			switch shouldUpdate {
+			case true:
+
+				if r.WriteRepairedDocsToDisk {
```
Comment (adamcfraser) [inline db/repair_bucket.go]: I'm not sure writing to disk is the best approach - if this is a REST call, retrieving the document from disk wherever Sync Gateway is running might not be trivial.  If we're trying to provide a way for people to roll back the change, how about an optional expiring backup of any modified documents in the bucket?  (as _sync:repair:[key])?

File: db/repair_bucket.go [hunk 4]
```diff
@@ -0,0 +1,228 @@
...
+					if writeTempFileErr != nil {
+						base.Warn("Error writing update doc to tmp file.  UpdatedDoc: %v.  Error: %v", updatedDoc, writeTempFileErr)
+					}
+
+					base.LogTo("CRUD", "Repair Doc (dry_run=%v).  Original doc written to: %+v, Post-repair doc written to: %+v", r.DryRun, origDocTempFile, updatedDocTempFile)
+
+				} else {
+
+					base.LogTo("CRUD", "Repair Doc (dry_run=%v)  Dumping doc contents directly into logs since WriteRepairedDocsToDisk disabled.", r.DryRun)
+
```
Comment (adamcfraser) [inline db/repair_bucket.go]: I'm not convinced logs are really the best place for full doc bodies + rev trees either - for a repair that touches a lot of documents in the bucket, it's particularly noisy.

File: rest/bulk_api.go [hunk 5]
```diff
@@ -244,6 +244,37 @@ func (h *handler) handleDump() error {
...
+	repairBucketParams := db.RepairBucketParams{}
+	if err := json.Unmarshal(body, &repairBucketParams); err != nil {
+		return fmt.Errorf("Error unmarsalling %v into RepairJobParams.  Err: %v", string(body), err)
+	}
+
+	repairBucket := db.NewRepairBucket(h.db.Bucket)
+
+	repairBucket.InitFrom(repairBucketParams)
+
+	_, repairDocsErr := repairBucket.RepairBucket()
```
Comment (adamcfraser) [inline rest/bulk_api.go]: I feel like the REST call should return details about what was changed.  At minimum a count, better would be a list of modified docs, even better would be a list of modified docs and a short summary the repair operation performed.

File: db/repair_bucket.go [hunk 6]
```diff
@@ -0,0 +1,228 @@
...
+// Params suitable for external (eg, HTTP) invocations to describe a specific RepairJob operation
+type RepairJobParams struct {
+	RepairJobType   RepairJobType          `json:"repair_job_type"`
+	RepairJobParams map[string]interface{} `json:"repair_job_params"`
+}
+
+// Given a Couchbase Bucket doc, transform the doc in some way to produce a new doc.
+// Also return a boolean to indicate whether a transformation took place, or any errors occurred.
+type DocTransformer func(doc *document) (transformedDoc *document, transformed bool, err error)
```
Comment (adamcfraser) [inline db/repair_bucket.go]: Should DocTransformer take raw bytes, instead of the marshalled document?  If in future we need to repair something that's breaking document unmarshalling, we won't be able to do it using this pattern.  It does mean that every DocTransformer needs to recode the unmarshal/marshal, but I'm thinking that's not too painful.

File: db/repair_bucket.go [hunk 7]
```diff
@@ -0,0 +1,228 @@
...
+		switch repairJobParams.RepairJobType {
+		case RepairRevTreeCycles:
+			r.AddRepairJob(RepairJobRevTreeCycles)
+		}
+	}
+
+	return r
+}
+
+func (r RepairBucket) RepairBucket() (repairedDocs []*document, err error) {
```
Comment (adamcfraser) [inline db/repair_bucket.go]: If the set of docs being repaired is large, do we have memory concerns associated with the repairedDocs array?

**Review by adamcfraser — CHANGES_REQUESTED** [review]

File: db/repair_bucket.go (hunk 2 above)
Comment (tleyden) [reply db/repair_bucket.go]: I ran goimports, no change.  Hmm...

File: db/repair_bucket.go (hunk 1 above)
Comment (tleyden) [reply db/repair_bucket.go]: Fixed

File: db/repair_bucket.go (hunk 6 above)
Comment (tleyden) [reply db/repair_bucket.go]: Done

File: db/repair_bucket.go (hunk 7 above)
Comment (tleyden) [reply db/repair_bucket.go]: Changed to return doc ids

File: db/repair_bucket.go (hunk 2 above)
Comment (adamcfraser) [reply db/repair_bucket.go]: It's just the empty lines between the standard library imports that need to be removed, I think.

File: db/repair_bucket.go (hunk 4 above)
Comment (tleyden) [reply db/repair_bucket.go]: Fixed.  If insertion of backup doc into bucket fails, it will fallback to dumping to logs.  Should never happen though.

File: db/repair_bucket.go (hunk 3 above)
Comment (tleyden) [reply db/repair_bucket.go]: Fixed

File: rest/bulk_api.go (hunk 5 above)
Comment (tleyden) [reply rest/bulk_api.go]: Fixed, with an asterisk.  See the "Hack:" explanation.

**Comment by tleyden** [comment]
@adamcfraser this is ready for another review pass.

File: db/repair_bucket.go [hunk 8]
```diff
@@ -0,0 +1,227 @@
...
+		backupOrDryRunDocId = fmt.Sprintf("sync:repair:backup:%v", docId)
+		contentToSave = originalDoc
+	}
+
+	doc, err := unmarshalDocument(docId, contentToSave)
+	if err != nil {
+		return backupOrDryRunDocId, fmt.Errorf("Error unmarshalling updated/original doc.  Err: %v", err)
+	}
+
+	expirySeconds := 60 * 60 // 1 hour
```
Comment (adamcfraser) [inline db/repair_bucket.go]: 24 hours

File: db/repair_bucket.go [hunk 9]
```diff
@@ -0,0 +1,227 @@
...
+
+	return results, nil
+}
+
+func (r RepairBucket) WriteRepairedDocsToBucket(docId string, originalDoc, updatedDoc []byte) (backupOrDryRunDocId string, err error) {
+
+	var contentToSave []byte
+
+	if r.DryRun {
+		backupOrDryRunDocId = fmt.Sprintf("sync:repair:dryrun:%v", docId)
```
Comment (adamcfraser) [inline db/repair_bucket.go]: Doc id should be _sync here and below

File: db/repair_bucket.go [hunk 10]
```diff
@@ -0,0 +1,227 @@
...
+			case true:
+
+				backupOrDryRunDocId, err := r.WriteRepairedDocsToBucket(key, currentValue, updatedDoc)
+				if err != nil {
+					base.LogTo("CRUD", "Repair Doc (dry_run=%v) Writing docs to bucket failed with error: %v.  Dumping raw contents.", r.DryRun, err)
+					base.LogTo("CRUD", "Original Doc before repair: %s", currentValue)
+					base.LogTo("CRUD", "Updated doc after repair: %s", updatedDoc)
+				}
+				if r.DryRun {
+					base.LogTo("CRUD", "Repair Doc: dry run result available in Bucket Doc: %v (auto-deletes in 1 hour)", backupOrDryRunDocId)
```
Comment (adamcfraser) [inline db/repair_bucket.go]: 24h

File: db/repair_bucket.go [hunk 11]
```diff
@@ -0,0 +1,227 @@
...
+					return nil, couchbase.UpdateCancel
+				} else {
+					return updatedDoc, nil
+				}
+			default:
+				return nil, couchbase.UpdateCancel
+			}
+
+		})
+
```
Comment (adamcfraser) [inline db/repair_bucket.go:134]: Do error checking for the error returned by Update.

If that's returning UpdateCancel for dry run, can move the 'update complete' logging after the error is checked.

File: db/repair_bucket.go [hunk 12]
```diff
@@ -0,0 +1,227 @@
...
+	// Check if rev history has cycles
+	containsCycles := doc.History.ContainsCycles()
+
+	if !containsCycles {
+		// nothing to repair
+		return nil, false, nil
+	}
+
+	// Repair it
+	if err := doc.History.Repair(); err != nil {
```
Comment (adamcfraser) [inline db/repair_bucket.go]: RepairCycles

File: db/repair_bucket.go [hunk 13]
```diff
@@ -0,0 +1,227 @@
...
+		return nil, false, err
+	}
+
+	transformedCBDoc, errMarshal := json.Marshal(doc)
+	if errMarshal != nil {
+		return nil, false, errMarshal
+	}
+
+	// Return original doc pointer since it was repaired in place
```
Comment (adamcfraser) [inline db/repair_bucket.go]: Update the comment based on returning []byte

File: db/repair_bucket_test.go [hunk 14]
```diff
@@ -0,0 +1,114 @@
...
+
+const (
+	docIdProblematicRevTree = "docIdProblematicRevTree"
+)
+
+func testBucketWithViewsAndBrokenDoc() (bucket base.Bucket, numDocs int) {
+
+	numDocsAdded := 0
+	bucket = testBucket()
+	log.Printf("installing views")
```
Comment (adamcfraser) [inline db/repair_bucket_test.go]: clean up logging

File: db/repair_bucket_test.go [hunk 15]
```diff
@@ -0,0 +1,114 @@
...
+	})
+
+	repairedDocs, err := repairBucket.RepairBucket()
+
+	assertNoError(t, err, fmt.Sprintf("Error repairing bucket: %v", err))
+	assert.True(t, len(repairedDocs) == 1)
+
+	// Now get the doc from the bucket
+	var value interface{}
+	_, errGetDoc := bucket.Get(docIdProblematicRevTree, &value)
```
Comment (adamcfraser) [inline db/repair_bucket_test.go]: GetRaw to skip the subsequent Marshal

File: db/repair_bucket_test.go [hunk 16]
```diff
@@ -0,0 +1,114 @@
...
+	repairedDocs, err := repairBucket.RepairBucket()
+
+	assertNoError(t, err, fmt.Sprintf("Unexpected error: %v", err))
+
+	// Both docs will be repaired due to the repairJob function that indiscriminately repairs all docs
+	assert.True(t, len(repairedDocs) == 2)
+
+}
+
+func TestRepairBucketRevTreeCycles(t *testing.T) {
```
Comment (adamcfraser) [inline db/repair_bucket_test.go]: Clone this as a test for dry run

File: db/repair_bucket_test.go [hunk 17]
```diff
@@ -0,0 +1,114 @@
...
+
+	base.EnableLogKey("CRUD")
```
Comment (adamcfraser) [inline db/repair_bucket_test.go:73]: Run this with two docs w/ cycles (can be the same body) to ensure everything is solid with loops/recursion.

File: rest/bulk_api.go [hunk 18]
```diff
@@ -244,6 +244,45 @@ func (h *handler) handleDump() error {
...
+		return fmt.Errorf("Error repairing bucket: %v", err)
+	}
+
+	resultMarshalled, err := json.Marshal(repairBucketResult)
+	if err != nil {
+		return fmt.Errorf("Error marshalling repairBucketResult: %+v", repairBucketResult)
+	}
+
+	h.setHeader("Content-Type", "application/json")
+	_, err = h.response.Write(resultMarshalled)
```
Comment (adamcfraser) [inline rest/bulk_api.go:280]: Try to add key for repair or backup docs in result.  Also useful to report whether dry run or doc changed.

**Review by adamcfraser — CHANGES_REQUESTED** [review]

File: db/repair_bucket_test.go (hunk 16 above)
Comment (tleyden) [reply db/repair_bucket_test.go]: Fixed

File: db/repair_bucket_test.go (hunk 17 above)
Comment (tleyden) [reply db/repair_bucket_test.go:73]: Fixed

File: rest/bulk_api.go (hunk 18 above)
Comment (tleyden) [reply rest/bulk_api.go:280]: Fixed

**Comment by tleyden** [comment]
@adamcfraser 2nd round of PR feedback addressed and pushed up

File: db/repair_bucket.go (hunk 11 above)
Comment (tleyden) [reply db/repair_bucket.go:134]: Done

**Comment by tleyden** [comment]
The drone build passed, going to merge

**Comment by tleyden** [comment]
[sgw-unix-build/3842](http://mobile.jenkins.couchbase.com/view/Sync_Gateway/job/sgw-unix-build/3842/) build in progress
