### PR TITLE
URL Encode usernames passed to /_user endpoint

### LINKED ISSUE #2870: /{db}/_user/{username} endpoint doesn't handle urlencoded usernames correctly
### Sync Gateway version  
1.4.1

### Operating system
Linux

### Config file
```javascript
```

### Log output
```
2017-08-31T23:17:36.348Z HTTP:  #2135: GET /db/_user/acm_auth0%7C592b99c46b81fe5bad864ad0  (ADMIN)
2017-08-31T23:17:36.350Z HTTP: #2135:     --> 404 missing  (2.1 ms)
2017-08-31T23:18:40.287Z HTTP:  #2137: GET /db/_user/acm_auth0%257C592b99c46b81fe5bad864ad0  (ADMIN)
2017-08-31T23:18:40.289Z HTTP+: #2137:     --> 200   (2.2 ms)
```
### Expected behavior
What should have happened?
The details for the registered user should be returned by the API.

### Actual behavior
What actually happened?
A `not_found` response is returned.

### Steps to reproduce
1.  Create a user with an encoded '|' in it's username i.e. `acm_auth0%7C592b99c46b81fe5bad864ad0`
2.  Query for all users via _user endpoint: `http://localhost:4985/db/_user/`
```
[
     "acm_auth0%7C592b99c46b81fe5bad864ad0"
]
```
3.  Query for that user returns "not found" "missing": `http://localhost:4985/db/_user/acm_auth0%7C592b99c46b81fe5bad864ad0`:
```
{
    error: "not_found",
    reason: "missing"
}
```
4 However, urlencoding the username again and querying for that user does return the information
`http://localhost:4985:/db/_user/acm_auth0%257C592b99c46b81fe5bad864ad0`:
```
{
    name: "acm_auth0%7C592b99c46b81fe5bad864ad0",
    all_channels: [
    "!"
    ],
    email: "tester@example.com"
}
```

Forum discussion: https://forums.couchbase.com/t/inspecting-user-role-channels-user-not-found/14012

### PR DESCRIPTION
**Pull request by ajres**
fixes #2870

### CODE REVIEW

File: rest/admin_api.go [hunk 1]
```diff
@@ -478,7 +479,8 @@ func (h *handler) deleteRole() error {
 
 func (h *handler) getUserInfo() error {
 	h.assertAdminOnly()
-	user, err := h.db.Authenticator().GetUser(internalUserName(mux.Vars(h.rq)["name"]))
+	eName := url.QueryEscape(mux.Vars(h.rq)["name"])
```
Comment (adamcfraser) [inline rest/admin_api.go]: Wouldn't this break for existing usernames with escapable characters that are currently valid in a username?  (e.g. `+`, `@`, `%`)?

**Review by adamcfraser — CHANGES_REQUESTED** [review]
