### PR TITLE
Convenience API to add attachments to a _removed document return appropriate error

### LINKED ISSUE #1685: Misleading error message when trying to add attachment to unavailable document
If a user tries to push an attachment to a document they don't have read access for, they get the error message:
`user defined top level properties beginning with '_' are not allowed in document body`

This is a result of the attempted retrieval of the original revision coming back with the _removed property (due to failed access).

### PR DESCRIPTION
**Pull request by ajres**
If a user uses the convenience API's to add attachments to a document that the user does not have read access to, return a more context appropriate error message.

fixes #1685

### CODE REVIEW

File: db/crud.go [hunk 1]
```diff
@@ -496,6 +496,13 @@ func (db *Database) updateDoc(docid string, allowImport bool, callback func(*doc
 			return
 		}
 
+		//Reject a body that contains the "_removed" property, this means that the user
+		//is trying to update a document they do not have read access to.
+		if body["_removed"] != nil {
+			err = base.HTTPErrorf(http.StatusNotFound, "Document revison is not accessible")
```
Comment (adamcfraser) [inline db/crud.go]: Typo in the return message ("revision").
