### PR TITLE
Fixes #3165

### LINKED ISSUE #3165: Blip replication does not work in DI mode
### Sync Gateway version
2.0.0 -> Tested with 2.0.0-683, 2.0.0-722

### Operating system
Centos

### Config file
```javascript
{
    "interface":":4984",
    "adminInterface": "0.0.0.0:4985",
    "maxIncomingConnections": 0,
    "maxCouchbaseConnections": 16,
    "maxFileDescriptors": 90000,
    "slowServerCallWarningThreshold": 500,
    "compressResponses": false,
    "log": ["CRUD+", "Cache+", "HTTP+", "Changes+"],
    "cluster_config": {
        "server":"http://192.168.33.10:8091",
        "data_dir":".",
        "bucket":"data-bucket",
        "username":"data-bucket",
        "password": "password"
    },
    "databases":{
        "db":{
            "unsupported": {
                "replicator_2": true
            },
            "revs_limit": 30,
            "rev_cache_size": 1000,
            "server":"http://192.168.33.10:8091",
            "bucket":"data-bucket",
            "username":"data-bucket",
            "password": "password",
            "channel_index":{
                "num_shards":16,
                "server":"http://192.168.33.10:8091",
                "bucket":"index-bucket",
                "username": "index-bucket",
                "password": "password",
                "writer":false
            }
        }
    }
}
```

### Log output
https://gist.github.com/sridevi-15/d1360d52e37ce6850b1f3006606c44f7

### Steps to reproduce
1.  Create db and docs in CBL 
2.  Enable blip replication on SG 
3.   start replication with continous to SG
4. Verify docs got replicated in SG

### Expected behavior
It should replicate to SG successfully and should be able to see docs in SG 

### Actual behavior
What actually happened?
Docs did not get replicated in SG and it throws an error in sg logs -> check the log output in gist

### PR DESCRIPTION
**Pull request by tleyden**
Fixes #3165

Verified by manual testing with SG in reader mode + SG Accel, using the Todo iOS sample app on the `feature/2.0` branch for replication.

Adding a unit test to repro is a fair amount of work, so that might be better done as a separate issue.

### CODE REVIEW

File: rest/blip_sync.go [hunk 1]
```diff
@@ -175,6 +175,16 @@ func (bh *blipHandler) handleSetCheckpoint(rq *blip.Message) error {
...
+
+	// Depeding on the db sequence type, use correct zero sequence for since value
+	// TODO #1: Add unit tests or spin off separate ticket
+	// TODO #2: Doesn't this need a valid SeqType field?  Seems to work without it
+	if bh.db.SequenceType == db.IntSequenceType {
+		since = db.SequenceID{Seq: 0}
+	} else {
+		since = db.SequenceID{Clock: base.NewSequenceClockImpl()}
+	}
+
```
Comment (adamcfraser) [inline rest/blip_sync.go]: It feels like we should pull the code: https://github.com/couchbase/sync_gateway/blob/4c6bd7044a31a82fcf8a44f02df9a52ecdd07ad5/rest/changes_api.go#L800-L804

into a helper method that could be called from changes_api and here - what do you think?

**Review by adamcfraser — CHANGES_REQUESTED** [review]

**Comment by tleyden** [comment]
@adamcfraser ok I've implemented that change.  Ready for another review.

**Review by adamcfraser — APPROVED** [review]
