### PR TITLE
Unmarshal document bodies with decoder.UseNumber()

### LINKED ISSUE #3783: Large Number Handled Incorrectly
### Sync Gateway version
2.1.0(121;a036bd8)

### Operating system
Either Windows 10 or macOS High Sierra (probably doesn't matter)

### Config file
Unused.  Just specified `--interface 0.0.0.0:4984`

### Log output
2018-10-05T10:23:54.170+09:00 [INF] HTTP:  #018: PUT /sync_gateway/test (as GUEST)

### Expected behavior
The number is stored correctly

### Actual behavior
An alternate number is somehow inserted

### Steps to reproduce
1.  Start Sync Gateway
2.  Send a PUT request for a document with the following body:  `{"number":9223372036854775807}`
3.  GET the document, and notice that the number is instead 9223372036854776000

### PR DESCRIPTION
**Pull request by adamcfraser**
Preserve number formatting in document bodies by always unmarshalling via decode with decoder.UseNumber.

Includes the following refactoring/cleanup:
- Only use db.Body when managing actual document bodies.
   - Created a new db.Revisions type for the most common other previous usage of db.Body, and added associated constants
- Always use Body.Unmarshal() to unmarshal document bodies using decoder instead of json.Unmarshal
- Adds unit tests for large number handling during CRUD, blip, import
- Adds tests to validate large number handling for sequences.  Adds ability to set up a test with a non-empty _sync:seq in the bucket

- [ ] Manifest needs updating after https://github.com/couchbase/go-blip/pull/35 is merged

Fixes #3783

### CODE REVIEW

**Comment by adamcfraser** [comment]
Failing build has reminded me that there's a go-blip dependency that also needs to be included (that's causing one of the new tests to fail).  Will get that PR submitted/merged and then update the manifest on this PR.

**Comment by adamcfraser** [comment]
http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/838/
http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/839/

File: db/revision.go [hunk 1]
```diff
@@ -22,13 +23,35 @@ import (
...
+
+	if len(data) == 0 {
+		b = &Body{}
+		return nil
+	}
+
+	// Use decoder for unmarshalling to preserve large numbers
+	decoder := json.NewDecoder(bytes.NewReader(data))
+	decoder.UseNumber()
+	if err := decoder.Decode(&b); err != nil {
```
Comment (bbrks) [inline db/revision.go]: `b` is already a pointer, taking the address again produces incorrect values when data = `[]byte("null")`

```go
if err := decoder.Decode(b); err != nil {
```

This test reproduces the issue:

```go
func TestBody_Unmarshal(t *testing.T) {
	var b Body

	err := b.Unmarshal([]byte(""))
	assertNoError(t, err, "expected no error when unmarshalling no bytes")
	assert.DeepEquals(t, b, Body{})

	err = b.Unmarshal([]byte("null"))
	assertNoError(t, err, "expected no error when unmarshalling null")
	assert.DeepEquals(t, b, Body(nil))

	err = b.Unmarshal([]byte("{}"))
	assertNoError(t, err, "expected no error when unmarshalling {}")
	assert.DeepEquals(t, b, Body{})

	err = b.Unmarshal([]byte(`{"test":true}`))
	assertNoError(t, err, "expected no error when unmarshalling example body")
	assert.DeepEquals(t, b, Body{"test": true})
}
```

File: db/revision.go [hunk 2]
```diff
@@ -22,13 +23,35 @@ import (
...
+const (
+	RevisionsStart = "start"
+	RevisionsIds   = "ids"
 )
 
 func (b *Body) Unmarshal(data []byte) error {
-	if err := json.Unmarshal(data, &b); err != nil {
+
+	if len(data) == 0 {
+		b = &Body{}
```
Comment (bbrks) [inline db/revision.go]: This isn't going to do what I think the intention was.
It will change the value of b, but only in this scope (and not for the caller of `b.Unmarshal`)

```go
*b = Body{}
```

The test in the next comment reproduces this

File: db/document.go [hunk 3]
```diff
@@ -132,7 +132,9 @@ func (doc *document) MarshalBody() ([]byte, error) {
 func unmarshalDocument(docid string, data []byte) (*document, error) {
 	doc := newDocument(docid)
 	if len(data) > 0 {
-		if err := json.Unmarshal(data, doc); err != nil {
+		decoder := json.NewDecoder(bytes.NewReader(data))
+		decoder.UseNumber()
+		if err := decoder.Decode(&doc); err != nil {
```
Comment (bbrks) [inline db/document.go]: `doc` is already a pointer, this is what is causing `TestImportNullDoc` to fail. produces incorrect values when data = []byte("null")

```go
if err := decoder.Decode(doc); err != nil { 
```

**Review by bbrks — CHANGES_REQUESTED** [review]
The failure in `TestImportNullDoc` (integration test w/ xattrs) is related to incorrect unmashaling of docs. I've left a couple of comments in the places it's occurring.

File: db/revision.go (hunk 1 above)
Comment (adamcfraser) [reply db/revision.go]: Good catch - thanks.

File: db/document.go (hunk 3 above)
Comment (adamcfraser) [reply db/document.go]: Fixed

File: db/revision.go (hunk 2 above)
Comment (adamcfraser) [reply db/revision.go]: Should actually be returning error here, to match json.Unmarshal behaviour.  Fixed and added to unit test.

**Comment by adamcfraser** [comment]
http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/840/
http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/841/

**Comment by adamcfraser** [comment]
What I thought was a minor fix on an existing unit test (TestImportWithStaleBucketDocCorrectExpiry wasn't iterating through its test cases) has actually exposed that the test wasn't working as intended.  Digging into whether this is something that can be easily fixed w/ this PR, or needs a separate ticket.

**Comment by adamcfraser** [comment]
Pushed up a temporary fix for the test (at least until we decide whether to fix #3804).  

Rerunning integration test:
http://uberjenkins.sc.couchbase.com/view/Build/job/sync-gateway-integration-master/842/

**Comment by adamcfraser** [comment]
@bbrks Integration tests are green - ready for another look.

**Review by bbrks — APPROVED** [review]
