### PR TITLE
Fix for backfill sequence handling

### LINKED ISSUE #2186: Same doc is sent twice to longpoll changes feed
### Sync Gateway version
Couchbase Sync Gateway/1.4(8;2c128aa) (ONLY occurs in with sg_accel)

### Operating system
CentOS 7

### Config file
```
    "interface":":4984",
    "adminInterface": "0.0.0.0:4985",
    "maxIncomingConnections": 0,
    "maxCouchbaseConnections": 16,
    "maxFileDescriptors": 90000,
    "slowServerCallWarningThreshold": 500,
    "compressResponses": false,
    "log": ["CRUD+", "Cache+", "HTTP+", "Changes+"],
    "verbose":"true",
    "cluster_config": {
        "server":"http://{{ couchbase_server_primary_node }}:8091",
        "data_dir":".",
        "bucket":"data-bucket"
    },
    "databases":{
        "db":{
            "server":"http://{{ couchbase_server_primary_node }}:8091",
            "bucket":"data-bucket",
            "feed_type":"DCPSHARD",
            "feed_params":{
                "num_shards":64
            },
            "channel_index":{
                "server":"http://{{ couchbase_server_primary_node }}:8091",
                "bucket":"index-bucket",
                "writer":{{ is_index_writer }}
            },
            "sync":
            `function(doc, oldDoc){
                if(doc._id == "access_doc_0") {
                    console.log("granting_access!");
                    access(["adam", "traun", "andy"], "NATGEO");
                }
                if(doc._id == "roles_doc_0") {
                    console.log("adding role to users!");
                    role(["adam", "traun", "andy"], "role:doc_access");
                }
                channel(doc, doc.channels);
            }`
        }
    }
}

```

### Expected behavior
Doc should only be sent to the changes feed once. 

### Actual behavior
I am issuing 2 changes requests:
1. Create a doc with a channel "NATGEO"
1. Create a user that does not have access to "NATGEO"
1. Start a longpoll changes feed for that user
1. Grant the user to "NATGEO" via the sync function
1. The changes feed should exit with doc and a last seq.
1. THE PROBLEM. If you issue another changes request with a since using that last_seq from above, the doc is returned again

Perhaps related?
I'm never seeing _user/ docs in the changes feed during this scenario

ex. 
1. `POST _changes {"feed": "longpoll", "since": "0", "timeout": 10000}`
```
{"results":[
{"seq":"1-0","id":"natgeo_0","changes":[{"rev":"1-f54c513673b8e636f36eeb6636e5ba3b"}]}
],
"last_seq":"1-0"}
```
1. `POST _changes {"feed": "longpoll", "since": "1-0", "timeout": 1000}`
```
{"results":[
{"seq":"2-0:682.1","id":"natgeo_0","changes":[{"rev":"1-f54c513673b8e636f36eeb6636e5ba3b"}]}
],
"last_seq":"2-0:682.1"}
```

### PR DESCRIPTION
**Pull request by adamcfraser**
Use a vb.seq comparison when determining whether to write a changes entry as backfill.

Fixes #2186.

### CODE REVIEW

**Comment by adamcfraser** [comment]
Unit test for the fix is included in https://github.com/couchbaselabs/sync-gateway-accel/pull/38.

File: db/index_changes.go [hunk 1]
```diff
@@ -402,9 +403,12 @@ func (db *Database) vectorChangesFeed(channel string, options ChangesOptions) (<
 		if options.Since.TriggeredByClock != nil {
 			for i := 0; i < len(log); i++ {
 				logEntry := log[i]
-				// If sequence is less than the backfillTo clock sequence for its vbucket, send as backfill (i.e. with triggered by)
-				isBackfill := logEntry.Sequence <= options.Since.TriggeredByClock.GetSequence(logEntry.VbNo)
 
+				// If vb.seq for the entry is earlier than the vb.seq that triggered this channel's backfill, send as backfill.
+				isBackfill := false
+				if logEntry.VbNo < options.Since.TriggeredByVbNo || (logEntry.VbNo == options.Since.TriggeredByVbNo && logEntry.Sequence < options.Since.TriggeredBy) {
```
Comment (tleyden) [inline db/index_changes.go]: This is a really complicated compound conditional, can it get reworked into something that's a little easier to grok?

maybe something like:

```
backfillNeeded := isBackFillNeeded(param1, param2...)

// If vb.seq for the entry is earlier than the vb.seq that triggered this channel's backfill,
// then a backfill is needed
func isBackFillNeeded(param1, param2, ...) boolean {

}

```

Comment (adamcfraser) [reply db/index_changes.go]: I originally had it as two separate if conditions, but at the time it seemed like overkill.  If you're finding it complicated, though, I agree it makes sense to rework.  I'll make that change.

File: db/index_changes.go [hunk 2]
```diff
@@ -402,9 +403,15 @@ func (db *Database) vectorChangesFeed(channel string, options ChangesOptions) (<
...
 				logEntry := log[i]
-				// If sequence is less than the backfillTo clock sequence for its vbucket, send as backfill (i.e. with triggered by)
-				isBackfill := logEntry.Sequence <= options.Since.TriggeredByClock.GetSequence(logEntry.VbNo)
 
+				// If vb.seq for the entry is earlier than the vb.seq that triggered this channel's backfill, send as backfill.
+				isBackfill := false
+				if base.CompareVbAndSequence(logEntry.VbNo, logEntry.Sequence, options.Since.TriggeredByVbNo, options.Since.TriggeredBy) == -1 {
+					isBackfill = true
+				}
+				if logEntry.VbNo < options.Since.TriggeredByVbNo || (logEntry.VbNo == options.Since.TriggeredByVbNo && logEntry.Sequence < options.Since.TriggeredBy) {
```
Comment (tleyden) [inline db/index_changes.go]: Can this get removed now? `if logEntry.VbNo < options.Since.TriggeredByVbNo || ...`

Comment (adamcfraser) [reply db/index_changes.go]: Sheesh - thanks for catching.  That's what I get for trying to push up the fix in between meetings.
