### PR TITLE
#3572 Fixes sgcollect_info bad request if upload_host is unset

### LINKED ISSUE #3572: _sg_collect_info rest end point : Throwing bad request error for a requirement for upload host with upload enabled to false
### Sync Gateway version
2.1.0-87

### Operating system
CentOS

### Config file
```{
    "interface":":4984",
    "adminInterface": "0.0.0.0:4985",
    "maxIncomingConnections": 0,
    "maxCouchbaseConnections": 16,
    "maxFileDescriptors": 90000,
    "slowServerCallWarningThreshold": 500,
    "compressResponses": false,
    "log": ["*"],
    "logging":{
        "redaction_level": "partial"
    },
    "databases":{
        "db":{
            "import_docs": "continuous",
            "enable_shared_bucket_access": true,


            "num_index_replicas": 0,
            "enable_shared_bucket_access": true,
            "server":"http://192.168.33.10:8091",
            "bucket":"data-bucket",
            "password": "password"
        }
    }
}

```

### Log output
{"error":"Bad Request","reason":"Invalid options used for sgcollect_info: upload must be set if upload_host is specified"}

### Steps to reproduce
1.  Execute curl command for sg version 2.1.0-87
2.  curl -v -X POST http://192.168.33.11:4985/_sgcollect_info -H 'Content-Type: application/json' -d '{"redact_level": "partial", "upload": false}'

### Expected behavior
Should not ask for upload_host as upload is false

### Actual behavior
sending response as bad request to provide upload host though upload is false. I see same response though upload parameter is not provided 

Also the Message should say "upload_host must be set if upload is specified" instead the message says "upload must be set if upload_host is specified"

### PR DESCRIPTION
**Pull request by bbrks**
Fixes #3572 

- Fixes case where the default value of `upload_host` was being populated before running the validation enforcing `upload=true` when `upload_host` was set.

### CODE REVIEW

**Review by tleyden — APPROVED** [review]
LGTM

File: rest/sgcollect.go [hunk 1]
```diff
@@ -146,12 +150,14 @@ func (c *sgCollectOptions) Validate() error {
...
 
+	// Customer number is required if uploading.
 	if c.Upload && c.Customer == "" {
 		return errors.New("customer must be set if upload is true")
 	}
 
-	if !c.Upload && c.UploadHost != "" {
-		return errors.New("upload must be set if upload_host is specified")
+	// If upload is false, and a custom upload_host is provided, ask them to set upload=true.
+	if c.UploadHost != defualtSGUploadHost && !c.Upload {
```
Comment (tleyden) [inline rest/sgcollect.go]: Looks like there's a typo: `default` vs `defualt`

Comment (adamcfraser) [inline rest/sgcollect.go]: Can this be simplified by moving 'setDefaults' to the end of Validate (or even have the caller of Validate invoke setDefaults?)

I think it's easier to reason about if 'Validate' is strictly validating the user input.

**Review by adamcfraser — APPROVED** [review]
